import { assertMissionTransition, buildArtifactId, registerArtifact, verifyArtifact } from './architecture-control-plane'
export type MissionStage='PLANNED'|'IN_PROGRESS'|'REVIEW'|'DELIVERED'|'VERIFIED'|'OWNER_APPROVAL'|'COMPLETED'
export const STAGE_ORDER:MissionStage[]=['PLANNED','IN_PROGRESS','REVIEW','DELIVERED','VERIFIED','OWNER_APPROVAL','COMPLETED']
export interface StageHandoff{stage:MissionStage;team:string;leader:string;status:'pending'|'active'|'done'|'blocked';startedAt:string|null;completedAt:string|null;notes:string;artifacts:string[];artifactRequired:ArtifactType;artifactValue:string|null;artifactVerified:boolean;artifactVerifiedAt:string|null;artifactVerifyError:string|null}
export type ArtifactType='url'|'transaction_id'|'message_id'|'file_path'|'data'|'none'
export interface MissionLogEntry{timestamp:string;actor:string;stage:MissionStage;message:string}
export interface ActiveMission{id:string;ownerId:string|null;title:string;description:string;revenueTarget:number;createdAt:string;updatedAt:string;currentStage:MissionStage;priority:'low'|'medium'|'high'|'critical';category:string;chain:StageHandoff[];log:MissionLogEntry[];threads:LeaderThread[]}
export interface LeaderThread{id:string;missionId:string;leaderId:string;leaderName:string;stage:MissionStage;messages:LeaderMessage[]}
export interface LeaderMessage{id:string;from:'OWNER'|'LEADER';author:string;text:string;timestamp:string}
const POD_LEADERS:Record<string,{leader:string;name:string}>= {scout:{leader:'SCOUT',name:'Intelligence & Research'},aurora:{leader:'AURORA',name:'Creation & Design'},echo:{leader:'ECHO',name:'Quality Assurance'},forge:{leader:'FORGE',name:'Engineering'},pulse:{leader:'PULSE',name:'Monitoring & Ops'},developer:{leader:'Developer',name:'System Health'},cybersecurity_r:{leader:'Cybersecurity R',name:'Compliance & Security'},revenue:{leader:'QUANTUM + AURORA',name:'Revenue (Passive Income)'}}
export const DEFAULT_CHAIN:Array<{stage:MissionStage;team:string;artifact:ArtifactType}>=[{stage:'PLANNED',team:'scout',artifact:'data'},{stage:'IN_PROGRESS',team:'aurora',artifact:'url'},{stage:'REVIEW',team:'echo',artifact:'data'},{stage:'DELIVERED',team:'forge',artifact:'url'},{stage:'VERIFIED',team:'pulse',artifact:'data'},{stage:'OWNER_APPROVAL',team:'pulse',artifact:'none'},{stage:'COMPLETED',team:'pulse',artifact:'none'}]
let store:ActiveMission[]=[];let seeded=false;const now=()=>new Date().toISOString();const uid=(p:string)=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`
function buildChain():StageHandoff[]{return DEFAULT_CHAIN.map(({stage,team,artifact})=>{const pod=POD_LEADERS[team]??{leader:team.toUpperCase(),name:team};return{stage,team,leader:pod.leader,status:'pending',startedAt:null,completedAt:null,notes:'',artifacts:[],artifactRequired:artifact,artifactValue:null,artifactVerified:false,artifactVerifiedAt:null,artifactVerifyError:null}})}
function seed(){if(seeded)return;seeded=true;store.push(...[
  {id:'mission_seed_affiliate_blog',ownerId:null,title:'Affiliate Blog Network — AI Tools Niche',description:'Build a 12-article SEO-optimized affiliate blog network targeting AI tools reviews.',revenueTarget:4200,createdAt:'2026-07-21T00:00:00.000Z',updatedAt:now(),currentStage:'IN_PROGRESS' as MissionStage,priority:'high' as const,category:'Affiliate'},
  {id:'mission_seed_saas_pdf_annotator',ownerId:null,title:'SaaS Micro-Tool — PDF Annotator',description:'Launch a $9/mo SaaS for PDF annotation with Stripe checkout.',revenueTarget:6800,createdAt:'2026-07-21T00:00:00.000Z',updatedAt:now(),currentStage:'DELIVERED' as MissionStage,priority:'critical' as const,category:'SaaS'},
].map((s)=>({ ...s, chain:buildChain(), log:[{timestamp:s.createdAt,actor:'SYSTEM',stage:'PLANNED' as MissionStage,message:`Mission created by CEO. Target: $${s.revenueTarget}/month.`}], threads:[] } as ActiveMission)))}
export function listActiveMissions(){seed();return store}export function getActiveMission(id:string){seed();return store.find(m=>m.id===id)||null}
export function createActiveMission(input:{title:string;description:string;ownerId?:string|null;revenueTarget?:number;priority?:ActiveMission['priority'];category?:string}):ActiveMission{seed();const m:ActiveMission={id:uid('mission'),ownerId:input.ownerId??null,title:input.title,description:input.description,revenueTarget:input.revenueTarget??0,createdAt:now(),updatedAt:now(),currentStage:'PLANNED',priority:input.priority??'medium',category:input.category??'General',chain:buildChain().map((c,i)=>i===0?{...c,status:'active',startedAt:now()}:c),log:[{timestamp:now(),actor:'CEO',stage:'PLANNED',message:`New mission created: ${input.title}.`}],threads:[]};store.unshift(m);return m}
export function advanceMissionStage(missionId:string):ActiveMission|null{seed();const m=store.find(x=>x.id===missionId);if(!m)return null;const idx=STAGE_ORDER.indexOf(m.currentStage);if(idx<0||idx>=STAGE_ORDER.length-1)return m;const current=m.chain.find(c=>c.stage===m.currentStage);if(!current)return m;if(current.artifactRequired!=='none'&&(!current.artifactValue||!current.artifactVerified)){current.status='blocked';current.artifactVerifyError=current.artifactVerifyError||`Cannot advance: ${current.artifactRequired} artifact is not verified.`;m.updatedAt=now();return m}current.status='done';current.completedAt=now();const nextStage=STAGE_ORDER[idx+1];assertMissionTransition(m.currentStage,nextStage);m.currentStage=nextStage;const next=m.chain.find(c=>c.stage===nextStage);if(next){next.status='active';next.startedAt=now()}m.updatedAt=now();m.log.push({timestamp:now(),actor:current.leader||'SYSTEM',stage:nextStage,message:`Stage advanced ${current.stage} → ${nextStage}.`});return m}
export function appendLeaderMessage(missionId:string,leaderId:string,from:'OWNER'|'LEADER',text:string):LeaderThread|null{seed();const m=store.find(x=>x.id===missionId);if(!m)return null;const current=m.chain.find(c=>c.stage===m.currentStage);const target=leaderId||current?.team||'';const info=POD_LEADERS[target]??{leader:target.toUpperCase(),name:target};let thread=m.threads.find(t=>t.leaderId===target&&t.stage===m.currentStage);if(!thread){thread={id:uid('thread'),missionId:m.id,leaderId:target,leaderName:info.leader,stage:m.currentStage,messages:[]};m.threads.push(thread)}thread.messages.push({id:uid('msg'),from,author:from==='OWNER'?'Owner':info.leader,text,timestamp:now()});m.log.push({timestamp:now(),actor:from==='OWNER'?'OWNER':info.leader,stage:m.currentStage,message:text.slice(0,200)});m.updatedAt=now();return thread}
export function getLeaderForCurrentStage(missionId:string){seed();const m=store.find(x=>x.id===missionId);if(!m)return null;const h=m.chain.find(c=>c.stage===m.currentStage);return h?{leaderId:h.team,leaderName:h.leader,stage:h.stage}:null}
export function approveMission(missionId:string):ActiveMission|null{seed();const m=store.find(x=>x.id===missionId);if(!m)return null;let guard=0;while(m.currentStage!=='OWNER_APPROVAL'&&m.currentStage!=='COMPLETED'&&guard++<10)advanceMissionStage(missionId);if(m.currentStage!=='OWNER_APPROVAL')return m;const h=m.chain.find(c=>c.stage===m.currentStage);if(h){h.status='done';h.completedAt=now();h.notes='Owner approved. Mission complete.'}assertMissionTransition('OWNER_APPROVAL','COMPLETED');m.currentStage='COMPLETED';m.updatedAt=now();return m}
export const POD_LEADER_MAP=POD_LEADERS
export function setStageArtifact(missionId:string,artifactValue:string,verified=false){seed();const m=store.find(x=>x.id===missionId);if(!m)return null;const h=m.chain.find(c=>c.stage===m.currentStage);if(!h)return null;h.artifactValue=artifactValue;h.artifactVerified=verified;h.artifactVerifiedAt=verified?now():null;h.artifactVerifyError=null;if(verified&&h.status==='blocked')h.status='active';m.updatedAt=now();void registerArtifact({artifactId:buildArtifactId({ventureId:null,missionId:m.id,stage:m.currentStage,artifactType:h.artifactRequired,value:artifactValue}),ventureId:null,missionId:m.id,stage:m.currentStage,producer:h.leader,consumers:[],artifactType:h.artifactRequired,value:artifactValue,version:1,supersedes:null}).then(async r=>{if(verified)await verifyArtifact(r.artifactId,h.leader,'mission-stage-verified')}).catch(()=>{});return m}
export async function verifyStageArtifact(missionId:string){seed();const m=store.find(x=>x.id===missionId);if(!m)return null;const h=m.chain.find(c=>c.stage===m.currentStage);if(!h)return null;if(!h.artifactValue){h.artifactVerifyError='No artifact value to verify';return m}if(h.artifactRequired==='none'){h.artifactVerified=true;h.artifactVerifiedAt=now();return m}h.artifactVerified=false;h.artifactVerifiedAt=null;h.artifactVerifyError='Use the canonical artifact verifier through the mission API or supervisor.';return m}
