/**
 * ai-providers-integration.ts — external provider tools.
 * These are tool-level integrations; CEO model execution uses the canonical
 * provider control plane in provider-control-plane.ts/provider-runtime-v2.ts.
 */
import type { ToolResult } from './tools'

function ok(preview: string, result: string): ToolResult { return { ok: true, preview, result } }
function fail(result: string): ToolResult { return { ok: false, preview: result.slice(0, 120), result } }
function needKey(name: string, envVar: string, url: string): ToolResult { return fail(`${name} requires ${envVar} env var. Get free key at ${url}. Set on Vercel → Settings → Environment Variables.`) }

/* ═══ LLM PROVIDER TOOLS ═══ */

export async function toolCerebrasLLM(args: any): Promise<ToolResult> {
  const key = process.env.CEREBRAS_API_KEY
  if (!key) return needKey('Cerebras', 'CEREBRAS_API_KEY', 'https://cloud.cerebras.ai')
  const { messages, model = 'llama3.1-8b' } = args ?? {}
  if (!messages) return fail('cerebras_llm requires "messages" array')
  try { const res = await fetch('https://api.cerebras.ai/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ model, messages, temperature: 0.3, max_tokens: 8000 }), signal: AbortSignal.timeout(60000) }); if (!res.ok) return fail(`Cerebras: HTTP ${res.status}`); const data = await res.json(); return ok(data.choices?.[0]?.message?.content?.slice(0, 80) ?? 'ok', `Cerebras (${model}):\n${data.choices?.[0]?.message?.content ?? ''}`) } catch (e: any) { return fail(`Cerebras: ${e?.message}`) }
}
export async function toolSambaNovaLLM(args: any): Promise<ToolResult> { const key = process.env.SAMBANOVA_API_KEY; if (!key) return needKey('SambaNova', 'SAMBANOVA_API_KEY', 'https://sambanova.ai'); const { messages, model = 'Meta-Llama-3.1-405B-Instruct' } = args ?? {}; if (!messages) return fail('sambanova_llm requires "messages" array'); try { const res = await fetch('https://api.sambanova.ai/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ model, messages, temperature: 0.3, max_tokens: 8000 }), signal: AbortSignal.timeout(60000) }); if (!res.ok) return fail(`SambaNova: HTTP ${res.status}`); const data = await res.json(); return ok(data.choices?.[0]?.message?.content?.slice(0, 80) ?? 'ok', `SambaNova (${model}):\n${data.choices?.[0]?.message?.content ?? ''}`) } catch (e: any) { return fail(`SambaNova: ${e?.message}`) } }
export async function toolTogetherLLM(args: any): Promise<ToolResult> { const key = process.env.TOGETHER_API_KEY; if (!key) return needKey('Together AI', 'TOGETHER_API_KEY', 'https://api.together.xyz'); const { messages, model = 'meta-llama/Llama-3.3-70B-Instruct-Turbo' } = args ?? {}; if (!messages) return fail('together_llm requires "messages" array'); try { const res = await fetch('https://api.together.xyz/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ model, messages, temperature: 0.3, max_tokens: 8000 }), signal: AbortSignal.timeout(60000) }); if (!res.ok) return fail(`Together AI: HTTP ${res.status}`); const data = await res.json(); return ok(data.choices?.[0]?.message?.content?.slice(0, 80) ?? 'ok', `Together AI (${model}):\n${data.choices?.[0]?.message?.content ?? ''}`) } catch (e: any) { return fail(`Together AI: ${e?.message}`) } }
export async function toolMistralLLM(args: any): Promise<ToolResult> { const key = process.env.MISTRAL_API_KEY; if (!key) return needKey('Mistral AI', 'MISTRAL_API_KEY', 'https://console.mistral.ai'); const { messages, model = 'mistral-large-latest' } = args ?? {}; if (!messages) return fail('mistral_llm requires "messages" array'); try { const res = await fetch('https://api.mistral.ai/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ model, messages, temperature: 0.3, max_tokens: 8000 }), signal: AbortSignal.timeout(60000) }); if (!res.ok) return fail(`Mistral: HTTP ${res.status}`); const data = await res.json(); return ok(data.choices?.[0]?.message?.content?.slice(0, 80) ?? 'ok', `Mistral (${model}):\n${data.choices?.[0]?.message?.content ?? ''}`) } catch (e: any) { return fail(`Mistral: ${e?.message}`) } }
export async function toolHuggingFaceLLM(args: any): Promise<ToolResult> { const key = process.env.HF_TOKEN || process.env.HUGGINGFACE_API_KEY; if (!key) return needKey('Hugging Face', 'HUGGINGFACE_API_KEY', 'https://huggingface.co/settings/tokens'); const { messages, model = 'meta-llama/Llama-3.3-70B-Instruct' } = args ?? {}; if (!messages) return fail('hf_llm requires "messages" array'); try { const res = await fetch(`https://api-inference.huggingface.co/models/${model}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ inputs: messages.map((m: any) => `${m.role}: ${m.content}`).join('\n'), parameters: { temperature: 0.3, max_new_tokens: 8000 } }), signal: AbortSignal.timeout(60000) }); if (!res.ok) return fail(`HuggingFace: HTTP ${res.status}`); const data = await res.json(); const content = Array.isArray(data) ? data[0]?.generated_text ?? '' : data?.generated_text ?? ''; return ok(content.slice(0, 80) || 'ok', `HuggingFace (${model}):\n${content}`) } catch (e: any) { return fail(`HuggingFace: ${e?.message}`) } }
export async function toolCloudflareLLM(args: any): Promise<ToolResult> {
  const key = process.env.CLOUDFLARE_API_KEY
  const accountId = process.env.CLOUDFLARE_ACCOUNT_ID
  if (!key || !accountId) return needKey('Cloudflare Workers AI', !key ? 'CLOUDFLARE_API_KEY' : 'CLOUDFLARE_ACCOUNT_ID', 'https://dash.cloudflare.com')
  const { messages, model = '@cf/google/gemma-4-26b-a4b-it' } = args ?? {}
  if (!messages) return fail('cloudflare_llm requires "messages" array')
  try {
    const res = await fetch(`https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(accountId)}/ai/run/${encodeURIComponent(model)}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ messages }), signal: AbortSignal.timeout(60000) })
    if (!res.ok) return fail(`Cloudflare: HTTP ${res.status}`)
    const data = await res.json(); const content = typeof data?.result?.response === 'string' ? data.result.response : typeof data?.result?.text === 'string' ? data.result.text : ''
    return ok(content.slice(0, 80) || 'ok', `Cloudflare (${model}):\n${content}`)
  } catch (e: any) { return fail(`Cloudflare: ${e?.message}`) }
}
export async function toolCohereLLM(args: any): Promise<ToolResult> { const key = process.env.COHERE_API_KEY; if (!key) return needKey('Cohere', 'COHERE_API_KEY', 'https://dashboard.cohere.com'); const { messages, model = 'command-r-plus' } = args ?? {}; if (!messages) return fail('cohere_llm requires "messages" array'); try { const res = await fetch('https://api.cohere.ai/v1/chat', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` }, body: JSON.stringify({ model, message: messages[messages.length - 1]?.content ?? '', chat_history: messages.slice(0, -1).map((m: any) => ({ role: m.role === 'assistant' ? 'CHATBOT' : 'USER', message: m.content })) }), signal: AbortSignal.timeout(60000) }); if (!res.ok) return fail(`Cohere: HTTP ${res.status}`); const data = await res.json(); return ok(data?.text?.slice(0, 80) ?? 'ok', `Cohere (${model}):\n${data?.text ?? ''}`) } catch (e: any) { return fail(`Cohere: ${e?.message}`) } }
