import type { ConversationDecisionContract } from './ceo-conversation-decision-contract'
import type { CognitiveLifecycleResult, PreRouteDecision, CeoExecutionContract } from './ceo-cognitive-contract'

export type CeoRequestOutcome = 'completed' | 'degraded' | 'cancelled' | 'timeout' | 'failed'
export type CeoGenerationStage = 'none' | 'primary' | 'refinement' | 'independent_review' | 'synthesis' | 'escalation'
export interface CeoGenerationDiagnostics { primaryOutputProduced: boolean; primaryQualityDecision: CognitiveLifecycleResult['quality']['decision'] | 'NOT_RUN'; finalOutputProduced: boolean; finalStage: CeoGenerationStage; escalationCount: number }
export interface CeoResponsePath { preRoute: PreRouteDecision['route'] | 'unknown'; cognitivePath: CognitiveLifecycleResult['decisionPlan']['path']; orchestrationOwner: CeoExecutionContract['orchestrationOwner']; intent: CeoExecutionContract['intent']; responseAction: ConversationDecisionContract['responseAction'] | null; evidenceClass: CeoExecutionContract['evidenceClass']; domain: CeoExecutionContract['domain'] }
export interface CeoRuntimeMetrics { schemaVersion: 5; responsePath: CeoResponsePath; generation: CeoGenerationDiagnostics; technicalReliability: { outcome: CeoRequestOutcome; providerAvailable: boolean; responseMs: number; providerAttemptCount: number; degraded: boolean; qualityDecision: CognitiveLifecycleResult['quality']['decision'] | 'NOT_RUN'; verificationStatus: CognitiveLifecycleResult['quality']['verificationStatus'] | 'NOT_RUN'; evidenceState: CognitiveLifecycleResult['evidenceState'] | 'NOT_RUN' }; cognitiveQuality: { measured: boolean; score: number; continuity: number; relevance: number; naturalness: number; toneAlignment: number; coherence: number; nonRepetition: number; initiative: number; referenceResolution: number; personalityConsistency: number; progression: number; cognitiveDepth: 0 | 1 | 2 | 3 | 4; semanticCompleteness: 'complete' | 'partial' | 'insufficient'; responseRegister: string; clarificationRequired: boolean } }
function clampScore(value: unknown, fallback: number): number { const numeric = typeof value === 'number' && Number.isFinite(value) ? value : fallback; return Math.round(Math.max(0, Math.min(100, numeric))) }
function nonNegativeFinite(value: unknown, fallback = 0): number { const numeric = typeof value === 'number' && Number.isFinite(value) ? value : fallback; return Math.round(Math.max(0, numeric)) }
function depthToScore(depth: ConversationDecisionContract['cognitiveDepth']): 0 | 1 | 2 | 3 | 4 { if (depth === 'direct') return 0; if (depth === 'contextual') return 1; if (depth === 'deep') return 2; return 4 }
const FALLBACK_CONTRACT: Partial<CeoExecutionContract> = { orchestrationOwner: 'ceo_lifecycle', intent: 'conversation', evidenceClass: 'none', domain: 'none' }
export function buildCeoRuntimeMetrics(input: { result: CognitiveLifecycleResult; decisionContract?: ConversationDecisionContract; outcome?: CeoRequestOutcome; preRoute?: PreRouteDecision; generation?: Partial<CeoGenerationDiagnostics> }): CeoRuntimeMetrics {
  const result = input.result
  const conversation = result.quality?.conversationQuality
  const contract = result.decisionPlan?.executionContract ?? FALLBACK_CONTRACT
  const technicalOutcome: CeoRequestOutcome = input.outcome ?? (result.degraded ? 'degraded' : result.provider ? 'completed' : 'failed')
  const depth = input.decisionContract ? depthToScore(input.decisionContract.cognitiveDepth) : Math.min(4, Math.max(0, result.decisionPlan?.cognitiveDepth ?? 0)) as 0 | 1 | 2 | 3 | 4
  const responsePath: CeoResponsePath = { preRoute: input.preRoute?.route ?? result.decisionPlan?.preRoute ?? 'unknown', cognitivePath: result.decisionPlan?.path ?? 'fast', orchestrationOwner: contract.orchestrationOwner ?? FALLBACK_CONTRACT.orchestrationOwner!, intent: contract.intent ?? input.decisionContract?.intent ?? FALLBACK_CONTRACT.intent!, responseAction: input.decisionContract?.responseAction ?? null, evidenceClass: contract.evidenceClass ?? FALLBACK_CONTRACT.evidenceClass!, domain: contract.domain ?? FALLBACK_CONTRACT.domain! }
  const generation: CeoGenerationDiagnostics = { primaryOutputProduced: input.generation?.primaryOutputProduced ?? true, primaryQualityDecision: input.generation?.primaryQualityDecision ?? result.quality?.decision ?? 'NOT_RUN', finalOutputProduced: input.generation?.finalOutputProduced ?? Boolean(result.content?.trim()), finalStage: input.generation?.finalStage ?? (result.decisionPlan?.reasoningStrategy === 'independent_review' ? 'synthesis' : result.decisionPlan?.reasoningStrategy === 'multi_pass' ? 'refinement' : 'primary'), escalationCount: Math.max(0, Math.floor(input.generation?.escalationCount ?? 0)) }
  const qualityDecision = result.quality?.decision ?? 'DEGRADED'
  const verificationStatus = result.quality?.verificationStatus ?? 'NOT_PERFORMED'
  const evidenceState = result.evidenceState ?? 'UNAVAILABLE'
  return { schemaVersion: 5, responsePath, generation, technicalReliability: { outcome: technicalOutcome, providerAvailable: Boolean(result.provider && result.model), responseMs: nonNegativeFinite(result.responseMs), providerAttemptCount: Array.isArray(result.attempts) ? Math.max(0, result.attempts.length) : 0, degraded: Boolean(result.degraded), qualityDecision, verificationStatus, evidenceState }, cognitiveQuality: { measured: Boolean(conversation), score: clampScore(conversation?.score, 0), continuity: clampScore(conversation?.continuity, 0), relevance: clampScore(conversation?.relevance, 0), naturalness: clampScore(conversation?.naturalness, 0), toneAlignment: clampScore(conversation?.toneAlignment, 0), coherence: clampScore(conversation?.coherence, 0), nonRepetition: clampScore(conversation?.nonRepetition, 0), initiative: clampScore(conversation?.initiative, 0), referenceResolution: clampScore(conversation?.referenceResolution, 0), personalityConsistency: clampScore(conversation?.personalityConsistency, 0), progression: clampScore(conversation?.progression, 0), cognitiveDepth: depth, semanticCompleteness: input.decisionContract?.completeness ?? (technicalOutcome === 'completed' || technicalOutcome === 'degraded' ? 'complete' : 'insufficient'), responseRegister: input.decisionContract?.responseRegister ?? 'conversational', clarificationRequired: input.decisionContract?.clarificationRequired ?? false } }
}
export function logCeoRuntimeMetrics(metrics: CeoRuntimeMetrics, requestId?: string): void { console.log('[ceo-runtime-metrics]', JSON.stringify({ requestId: requestId ?? null, ...metrics })) }
export function logCeoTechnicalOutcome(outcome: CeoRequestOutcome, requestId: string, responseMs = 0): void { const emptyResult = { provider: null, model: null, responseMs, attempts: [] as string[], decisionPlan: { cognitiveDepth: 0, preRoute: 'fast', path: 'fast', executionContract: { orchestrationOwner: 'ceo_lifecycle', intent: 'conversation', evidenceClass: 'none', domain: 'none' } }, quality: { decision: 'DEGRADED', verificationStatus: 'NOT_PERFORMED', evidenceState: 'UNAVAILABLE' }, evidenceState: 'UNAVAILABLE', degraded: outcome === 'degraded', content: '' } as unknown as CognitiveLifecycleResult; logCeoRuntimeMetrics(buildCeoRuntimeMetrics({ result: emptyResult, outcome }), requestId) }
