import type { ConversationDecisionContract } from './ceo-conversation-decision-contract'
import type { CognitiveLifecycleResult, PreRouteDecision } from './ceo-cognitive-contract'

export type CeoRequestOutcome = 'completed' | 'degraded' | 'cancelled' | 'timeout' | 'failed'
export type CeoGenerationStage = 'none' | 'primary' | 'refinement' | 'independent_review' | 'synthesis' | 'escalation'
export interface CeoGenerationDiagnostics { primaryOutputProduced: boolean; primaryQualityDecision: CognitiveLifecycleResult['quality']['decision'] | 'NOT_RUN'; finalOutputProduced: boolean; finalStage: CeoGenerationStage; escalationCount: number }
export interface CeoResponsePath { preRoute: PreRouteDecision['route'] | 'unknown'; cognitivePath: CognitiveLifecycleResult['decisionPlan']['path']; orchestrationOwner: CognitiveLifecycleResult['decisionPlan']['executionContract']['orchestrationOwner']; intent: CognitiveLifecycleResult['decisionPlan']['executionContract']['intent']; responseAction: ConversationDecisionContract['responseAction'] | null; evidenceClass: CognitiveLifecycleResult['decisionPlan']['executionContract']['evidenceClass']; domain: CognitiveLifecycleResult['decisionPlan']['executionContract']['domain'] }
export interface CeoRuntimeMetrics { schemaVersion: 5; responsePath: CeoResponsePath; generation: CeoGenerationDiagnostics; technicalReliability: { outcome: CeoRequestOutcome; providerAvailable: boolean; responseMs: number; providerAttemptCount: number; degraded: boolean; qualityDecision: CognitiveLifecycleResult['quality']['decision'] | 'NOT_RUN'; verificationStatus: CognitiveLifecycleResult['quality']['verificationStatus'] | 'NOT_RUN'; evidenceState: CognitiveLifecycleResult['evidenceState'] | 'NOT_RUN' }; cognitiveQuality: { measured: boolean; score: number; continuity: number; relevance: number; naturalness: number; toneAlignment: number; coherence: number; nonRepetition: number; initiative: number; referenceResolution: number; personalityConsistency: number; progression: number; cognitiveDepth: 0 | 1 | 2 | 3 | 4; semanticCompleteness: 'complete' | 'partial' | 'insufficient'; responseRegister: string; clarificationRequired: boolean } }
function clampScore(value: unknown, fallback: number): number { const numeric = typeof value === 'number' && Number.isFinite(value) ? value : fallback; return Math.round(Math.max(0, Math.min(100, numeric))) }
function nonNegativeFinite(value: unknown, fallback = 0): number { const numeric = typeof value === 'number' && Number.isFinite(value) ? value : fallback; return Math.round(Math.max(0, numeric)) }
function depthToScore(depth: ConversationDecisionContract['cognitiveDepth']): 0 | 1 | 2 | 3 | 4 { if (depth === 'direct') return 0; if (depth === 'contextual') return 1; if (depth === 'deep') return 2; return 4 }
export function buildCeoRuntimeMetrics(input: { result: CognitiveLifecycleResult; decisionContract?: ConversationDecisionContract; outcome?: CeoRequestOutcome; preRoute?: PreRouteDecision; generation?: Partial<CeoGenerationDiagnostics> }): CeoRuntimeMetrics {
  const conversation = input.result.quality.conversationQuality
  const technicalOutcome: CeoRequestOutcome = input.outcome ?? (input.result.degraded ? 'degraded' : input.result.provider ? 'completed' : 'failed')
  const depth = input.decisionContract ? depthToScore(input.decisionContract.cognitiveDepth) : Math.min(4, Math.max(0, input.result.decisionPlan.cognitiveDepth)) as 0 | 1 | 2 | 3 | 4
  const responsePath: CeoResponsePath = { preRoute: input.preRoute?.route ?? input.result.decisionPlan.preRoute ?? 'unknown', cognitivePath: input.result.decisionPlan.path, orchestrationOwner: input.result.decisionPlan.executionContract.orchestrationOwner, intent: input.result.decisionPlan.executionContract.intent, responseAction: input.decisionContract?.responseAction ?? null, evidenceClass: input.result.decisionPlan.executionContract.evidenceClass, domain: input.result.decisionPlan.executionContract.domain }
  const generation: CeoGenerationDiagnostics = { primaryOutputProduced: input.generation?.primaryOutputProduced ?? true, primaryQualityDecision: input.generation?.primaryQualityDecision ?? input.result.quality.decision, finalOutputProduced: input.generation?.finalOutputProduced ?? Boolean(input.result.content.trim()), finalStage: input.generation?.finalStage ?? (input.result.decisionPlan.reasoningStrategy === 'independent_review' ? 'synthesis' : input.result.decisionPlan.reasoningStrategy === 'multi_pass' ? 'refinement' : 'primary'), escalationCount: Math.max(0, Math.floor(input.generation?.escalationCount ?? 0)) }
  return { schemaVersion: 5, responsePath, generation, technicalReliability: { outcome: technicalOutcome, providerAvailable: Boolean(input.result.provider && input.result.model), responseMs: nonNegativeFinite(input.result.responseMs), providerAttemptCount: Math.max(0, input.result.attempts.length), degraded: input.result.degraded, qualityDecision: input.result.quality.decision, verificationStatus: input.result.quality.verificationStatus, evidenceState: input.result.evidenceState }, cognitiveQuality: { measured: Boolean(conversation), score: clampScore(conversation?.score, 0), continuity: clampScore(conversation?.continuity, 0), relevance: clampScore(conversation?.relevance, 0), naturalness: clampScore(conversation?.naturalness, 0), toneAlignment: clampScore(conversation?.toneAlignment, 0), coherence: clampScore(conversation?.coherence, 0), nonRepetition: clampScore(conversation?.nonRepetition, 0), initiative: clampScore(conversation?.initiative, 0), referenceResolution: clampScore(conversation?.referenceResolution, 0), personalityConsistency: clampScore(conversation?.personalityConsistency, 0), progression: clampScore(conversation?.progression, 0), cognitiveDepth: depth, semanticCompleteness: input.decisionContract?.completeness ?? (technicalOutcome === 'completed' || technicalOutcome === 'degraded' ? 'complete' : 'insufficient'), responseRegister: input.decisionContract?.responseRegister ?? 'conversational', clarificationRequired: input.decisionContract?.clarificationRequired ?? false } }
}
export function logCeoRuntimeMetrics(metrics: CeoRuntimeMetrics, requestId?: string): void { console.log('[ceo-runtime-metrics]', JSON.stringify({ requestId: requestId ?? null, ...metrics })) }
export function logCeoTechnicalOutcome(outcome: CeoRequestOutcome, requestId: string, responseMs = 0): void { const emptyResult = { provider: null, model: null, responseMs, attempts: [] as string[], decisionPlan: { cognitiveDepth: 0, preRoute: 'fast', path: 'fast', executionContract: { orchestrationOwner: 'ceo_lifecycle', intent: 'conversation', evidenceClass: 'none', domain: 'none' } }, quality: { decision: 'NOT_RUN', verificationStatus: 'NOT_RUN', evidenceState: 'NOT_RUN', conversationQuality: undefined }, evidenceState: 'NOT_RUN', degraded: outcome === 'degraded', content: '' } as unknown as CognitiveLifecycleResult; logCeoRuntimeMetrics(buildCeoRuntimeMetrics({ result: emptyResult, outcome }), requestId) }
