import type { EvidenceFreshness, EvidenceProfile, EvidenceScope } from './ceo-cognitive-contract'
import type { CeoEvidenceTruthState } from './ceo-system-contract'

export type EvidenceSourceType = 'sec_companyfacts' | 'sec_filing' | 'company_ir' | 'market_data' | 'news' | 'web' | 'page'
export type EvidenceAssessmentState = CeoEvidenceTruthState
export interface EvidenceProvenance { url: string; title: string; sourceType: EvidenceSourceType; sourceTier: 1 | 2 | 3 | 4; retrievedAt: number; publishedAt?: number }
export interface EvidenceSource { id: string; url: string; title: string; sourceType: EvidenceSourceType; sourceTier: 1 | 2 | 3 | 4; retrievedAt: number; publishedAt?: number; sourceAgeMs?: number; text: string; claimCandidates: string[]; provenance: EvidenceProvenance[] }
export interface EvidenceClaimCandidate { claim: string; sourceIds: string[]; sourceUrls: string[]; observedAt?: number; verifiedAt?: number; confidence?: number; state?: EvidenceAssessmentState; contradictionSourceIds?: string[] }
export interface EvidenceBundle { scope: EvidenceScope; profile: EvidenceProfile; createdAt: number; sources: EvidenceSource[]; claims: EvidenceClaimCandidate[]; freshness: EvidenceFreshness; contextText: string; sufficient: boolean }

const PROFILE_MAX_AGE_MS: Record<EvidenceProfile, number> = { none: 0, general_research: 60 * 60 * 1000, public_equity: 15 * 60 * 1000, market_current: 15 * 60 * 1000, news_recent: 30 * 60 * 1000, competitor_research: 6 * 60 * 60 * 1000, business_due_diligence: 24 * 60 * 60 * 1000 }
function canonicalizeUrl(input: string): string { try { const url = new URL(input.trim()); url.hash = ''; for (const key of [...url.searchParams.keys()]) if (/^(utm_|fbclid$|gclid$|ref$|source$)/i.test(key)) url.searchParams.delete(key); return url.toString().replace(/\/$/, '') } catch { return input.trim() } }
function stableSourceId(url: string, index: number): string { let hash = 2166136261; for (let i = 0; i < url.length; i += 1) hash = Math.imul(hash ^ url.charCodeAt(i), 16777619); return `S${index + 1}-${(hash >>> 0).toString(16)}` }
function extractClaimCandidates(text: string): string[] { return text.split(/\n+/).map((line) => line.trim()).filter((line) => line.length >= 25 && /\b(?:revenue|sales|earnings|eps|cash|debt|assets|liabilities|income|loss|margin|guidance|backlog|price|market cap|valuation|shares|regulation|competitor|customer)\b/i.test(line)).slice(0, 20) }
export function sourceTierForUrl(url: string): 1 | 2 | 3 | 4 { try { const host = new URL(url).hostname.toLowerCase(); if (host === 'sec.gov' || host.endsWith('.sec.gov') || host === 'data.sec.gov') return 1; if (host === 'nasdaq.com' || host.endsWith('.nasdaq.com') || host === 'nyse.com' || host.endsWith('.nyse.com') || host === 'stockanalysis.com' || host.endsWith('.stockanalysis.com')) return 2; if (host === 'reuters.com' || host.endsWith('.reuters.com') || host === 'bloomberg.com' || host.endsWith('.bloomberg.com') || host === 'wsj.com' || host.endsWith('.wsj.com') || host === 'cnbc.com' || host.endsWith('.cnbc.com')) return 3 } catch { return 4 }; return 4 }
export function createEvidenceSource(input: { url: string; title: string; sourceType: EvidenceSourceType; sourceTier?: 1 | 2 | 3 | 4; retrievedAt?: number; publishedAt?: number; text: string; id?: string }): EvidenceSource { const url = canonicalizeUrl(input.url), retrievedAt = input.retrievedAt ?? Date.now(), sourceTier = input.sourceTier ?? sourceTierForUrl(url), cleanText = input.text.trim().slice(0, 12000); return { id: input.id ?? stableSourceId(url, 0), url, title: input.title.trim() || url, sourceType: input.sourceType, sourceTier, retrievedAt, publishedAt: input.publishedAt, sourceAgeMs: input.publishedAt ? Math.max(0, retrievedAt - input.publishedAt) : undefined, text: cleanText, claimCandidates: extractClaimCandidates(cleanText), provenance: [{ url, title: input.title.trim() || url, sourceType: input.sourceType, sourceTier, retrievedAt, publishedAt: input.publishedAt }] } }
export function buildEvidenceBundle(input: { profile: EvidenceProfile; sources: EvidenceSource[]; scope?: EvidenceScope; minimumSources?: number; minimumTierOneSources?: number }): EvidenceBundle { const createdAt = Date.now(), deduped = new Map<string, EvidenceSource>(); input.sources.forEach((source, index) => { const url = canonicalizeUrl(source.url), normalized = { ...source, url, provenance: source.provenance.map((entry) => ({ ...entry, url: canonicalizeUrl(entry.url) })) }; if (!deduped.has(url)) deduped.set(url, { ...normalized, id: stableSourceId(url, index) }) }); const sources = [...deduped.values()], claims: EvidenceClaimCandidate[] = []; for (const source of sources) for (const claim of source.claimCandidates.slice(0, 12)) claims.push({ claim, sourceIds: [source.id], sourceUrls: [source.url], observedAt: source.retrievedAt, confidence: source.sourceTier === 1 ? 0.95 : source.sourceTier === 2 ? 0.85 : source.sourceTier === 3 ? 0.75 : 0.55, state: 'unverified' }); const observedAt = sources.length > 0 ? sources.reduce((latest, source) => Math.max(latest, source.retrievedAt), 0) : createdAt, profileMaxAge = PROFILE_MAX_AGE_MS[input.profile], minimumSources = input.minimumSources ?? (input.profile === 'public_equity' ? 3 : input.profile === 'none' ? 0 : 2), minimumTierOneSources = input.minimumTierOneSources ?? (input.profile === 'public_equity' ? 1 : 0), sufficient = sources.length >= minimumSources && sources.filter((source) => source.sourceTier <= 1).length >= minimumTierOneSources; const contextText = sources.map((source) => `[${source.id}] ${source.title}\nURL: ${source.url}\nTier: ${source.sourceTier}\nRetrieved: ${new Date(source.retrievedAt).toISOString()}${source.publishedAt ? `\nPublished: ${new Date(source.publishedAt).toISOString()}` : ''}\n\n${source.text.slice(0, 2800)}`).join('\n\n---\n\n').slice(0, 16000); return { scope: input.scope ?? 'external_web', profile: input.profile, createdAt, sources, claims, freshness: { observedAt, maxAgeMs: profileMaxAge }, contextText, sufficient } }
export function assessEvidenceClaim(input: { claim: EvidenceClaimCandidate; now?: number; maxAgeMs: number; verified?: boolean; contradictorySourceIds?: string[] }): EvidenceClaimCandidate { const now = input.now ?? Date.now(), observedAt = input.claim.observedAt ?? now, stale = now - observedAt > input.maxAgeMs, contradictionSourceIds = [...new Set(input.contradictorySourceIds ?? input.claim.contradictionSourceIds ?? [])]; const state: EvidenceAssessmentState = contradictionSourceIds.length ? 'contradictory' : input.verified ? 'verified' : stale ? 'stale' : 'unverified'; return { ...input.claim, state, verifiedAt: input.verified ? now : input.claim.verifiedAt, contradictionSourceIds } }
export function isEvidenceDecisionGrade(claim: EvidenceClaimCandidate): boolean { return claim.state === 'verified' && (claim.confidence ?? 0) >= 0.75 && !(claim.contradictionSourceIds?.length) }
export function renderEvidenceBundleForPrompt(bundle: EvidenceBundle): string {
  if (!bundle.sources.length) return 'No external evidence was acquired.'
  const now = Date.now()
  const staleClaimCount = bundle.claims.filter((claim) => assessEvidenceClaim({ claim, now, maxAgeMs: bundle.freshness.maxAgeMs }).state === 'stale').length
  const freshnessLine = staleClaimCount > 0
    ? `Freshness: ${staleClaimCount} of ${bundle.claims.length} extracted claim(s) are older than this profile's freshness window and should be treated as potentially outdated, not current.`
    : `Freshness: all extracted claims are within this profile's freshness window as of observation time.`
  return [`EVIDENCE BUNDLE: ${bundle.profile}`, `Observed: ${new Date(bundle.freshness.observedAt).toISOString()}`, `Sufficient: ${bundle.sufficient ? 'yes' : 'no'}`, freshnessLine, 'Source markers are authoritative. Do not create citations that are not present in this bundle.', 'Claims are unverified until the governed verification step upgrades them.', bundle.contextText].join('\n\n')
}