import type { PersistedConversationRow } from './ceo-context-composer'

export type ConversationReferenceKind = 'ordinal' | 'temporal' | 'continuation' | 'pronoun' | 'demonstrative' | 'contextual'
export interface EnumeratedItem { index: number; ordinal: number; text: string; sourceRole: 'user' | 'assistant'; sourceTimestamp: number; listId: string }
export interface ReferenceCandidate { text: string; sourceRole: 'user' | 'assistant'; sourceTimestamp: number; score: number; reasons: string[] }
export interface ReferenceResolution { phrase: string; kind: ConversationReferenceKind; resolvedText: string | null; confidence: number; sourceRole?: 'user' | 'assistant'; ambiguous: boolean; candidates: ReferenceCandidate[] }
export interface ConversationThreadRecord { id: string; title: string; topic: string; entities: string[]; currentObjective: string; lastAssistantReply?: string; unresolvedQuestions: string[]; decisions: string[]; lastTouchedAt: number; status: 'active' | 'paused' | 'resolved' | 'superseded' | 'abandoned' }

const REFERENCE_PATTERNS = [/\b(it|this|that|these|those)\b/i, /\bthe\s+(first|second|third|last|other)\s+(one|thing|problem|issue|option|idea)\b/i, /\b(same\s+(thing|issue|problem))\b/i, /\bwhat\s+we\s+(said|did|decided|wanted)\b/i, /\boriginally\b/i, /\b(yesterday|today|earlier|before|last\s+week|two\s+days?\s+ago)\b/i, /\bcontinue\b/i, /\bthe\s+current\s+(issue|problem|topic|thread)\b/i, /\bwhat(?:'s|\s+is)?\s+about\s+the\s+[a-z][a-z\s]{2,40}\b/i]
const CURRENT_TOPIC_PATTERN = /\bthe\s+current\s+(?:issue|problem|topic|thread)\b/i
const NOUN_PHRASE_REFERENCE_PATTERN = /\bwhat(?:'s|\s+is)?\s+about\s+the\s+([a-z][a-z\s]{2,40}?)\??\s*$/i
const ORDINAL_PATTERN = /\bthe\s+(first|second|third|last|other)\s+(one|thing|problem|issue|option|idea)\b/i
const TEMPORAL_PATTERN = /\b(yesterday|today|earlier|before|last\s+week|two\s+days?\s+ago)\b/i
const CONTINUE_PATTERN = /^\s*(?:please\s+)?continue(?:\s+with\s+(?:the|this|that)\s+(?:decision|thread|topic|issue|problem))?\.?\s*$/i
const PRONOUN_PATTERN = /\b(it|they|them|this|that|these|those|same\s+(?:thing|issue|problem))\b/i
const STOPWORDS = new Set(['about','after','again','also','because','before','being','between','could','from','have','into','more','most','other','should','that','their','there','these','they','this','those','through','under','what','when','where','which','while','with','would','your','please','then','than','just','like','really','very','doing','does','doesnt','dont','you','are','how','why','can','tell','give','make','want','were','will','been','them','theyre','has','had','same','option','thing','problem','issue'])
function normalize(value:string):string{return value.replace(/\s+/g,' ').trim()}
function timestamp(value:PersistedConversationRow['createdAt']):number{if(value instanceof Date)return value.getTime();if(typeof value==='number')return value;const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:0}
function tokenize(value:string):Set<string>{return new Set(normalize(value).toLowerCase().split(/[^a-z0-9]+/).filter((token)=>token.length>=4&&!STOPWORDS.has(token)))}
function overlap(a:string,b:string):number{const left=tokenize(a),right=tokenize(b);if(!left.size||!right.size)return 0;let matches=0;for(const token of left)if(right.has(token))matches+=1;return matches/Math.max(1,Math.min(left.size,right.size))}
function detectedReference(message:string):string|null{for(const pattern of REFERENCE_PATTERNS){const match=message.match(pattern);if(match?.[0])return normalize(match[0])}return null}
function kindFor(message:string):ConversationReferenceKind{if(ORDINAL_PATTERN.test(message))return'ordinal';if(TEMPORAL_PATTERN.test(message))return'temporal';if(CONTINUE_PATTERN.test(message))return'continuation';if(/\b(it|they|them)\b/i.test(message))return'pronoun';if(/\b(this|that|these|those|same)\b/i.test(message))return'demonstrative';return'contextual'}
function dayKey(timestampMs:number,timeZone='UTC'):string{return new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(timestampMs))}
function offsetCalendarDay(key:string,deltaDays:number):string|null{const match=key.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!match)return null;const base=Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]));const shifted=new Date(base+deltaDays*86_400_000);return`${shifted.getUTCFullYear()}-${String(shifted.getUTCMonth()+1).padStart(2,'0')}-${String(shifted.getUTCDate()).padStart(2,'0')}`}

function extractProseListItems(text:string):string[]|null{const match=text.match(/(?::|\bare\b|\binclude[s]?\b)\s*([a-z][a-z0-9 ,]{4,140})[.!]?$/i);if(!match)return null;const tail=match[1].replace(/\s+and\s+/i,', ');const parts=tail.split(',').map((part)=>normalize(part)).filter((part)=>part.length>=2&&part.length<=60);return parts.length>=2?parts:null}
const LIST_HEADER_RE = /^(?:options?|alternatives?|choices?|priorities?|steps?|approaches?|plans?|items?)\s*:?\s*$/i
export function extractEnumeratedItems(rows:readonly PersistedConversationRow[],maxItems=24):EnumeratedItem[]{const items:EnumeratedItem[]=[];let listSerial=0;for(const row of rows.slice(-24)){if(row.role!=='user'&&row.role!=='assistant')continue;const sourceTimestamp=timestamp(row.createdAt);let currentListId=`list-${listSerial}`;let foundNumberedLine=false;let sawListHeader=false;const lines=row.content.split(/\r?\n/).map(normalize);for(const line of lines){if(LIST_HEADER_RE.test(line)){sawListHeader=true;continue}const match=line.match(/^(\d{1,2})[.)]\s+(.+)$/);if(!match)continue;foundNumberedLine=true;const ordinal=Number(match[1]);if(!Number.isInteger(ordinal)||ordinal<1||ordinal>maxItems)continue;if(ordinal===1 || sawListHeader){listSerial+=1;currentListId=`list-${listSerial}`;sawListHeader=false}items.push({index:items.length,ordinal,text:normalize(match[2]),sourceRole:row.role as'user'|'assistant',sourceTimestamp,listId:currentListId});if(items.length>=maxItems)return items}sawListHeader=false;if(!foundNumberedLine){const prose=extractProseListItems(normalize(row.content));if(prose){listSerial+=1;currentListId=`list-${listSerial}`;prose.forEach((text,i)=>items.push({index:items.length,ordinal:i+1,text,sourceRole:row.role as'user'|'assistant',sourceTimestamp,listId:currentListId}))}}}return items}
function latestList(items:EnumeratedItem[]):EnumeratedItem[]{if(!items.length)return[];const latestId=items.at(-1)!.listId;return items.filter((item)=>item.listId===latestId)}
export function resolveOrdinalReference(message:string,rows:readonly PersistedConversationRow[]):ReferenceResolution|null{const match=message.match(ORDINAL_PATTERN);if(!match)return null;const word=match[1].toLowerCase();const ordinal=word==='first'?1:word==='second'?2:word==='third'?3:null;const items=latestList(extractEnumeratedItems(rows));if(!items.length)return{phrase:normalize(match[0]),kind:'ordinal',resolvedText:null,confidence:0,ambiguous:true,candidates:[]};const selected=ordinal?[...items].reverse().find((item)=>item.ordinal===ordinal):items.at(-1);if(!selected)return{phrase:normalize(match[0]),kind:'ordinal',resolvedText:null,confidence:0,ambiguous:true,candidates:[]};return{phrase:normalize(match[0]),kind:'ordinal',resolvedText:selected.text,confidence:0.98,sourceRole:selected.sourceRole,ambiguous:false,candidates:[{text:selected.text,sourceRole:selected.sourceRole,sourceTimestamp:selected.sourceTimestamp,score:0.98,reasons:['explicit numbered-list ordinal','resolved within latest coherent list']}]}}
export function resolveTemporalReference(message:string,rows:readonly PersistedConversationRow[],options:{nowMs?:number;timeZone?:string}={}):ReferenceResolution|null{const match=message.match(TEMPORAL_PATTERN);if(!match)return null;const phrase=normalize(match[1]);const timeZone=options.timeZone??'UTC';const anchor=options.nowMs??Math.max(0,...rows.map((row)=>timestamp(row.createdAt)));if(!anchor)return{phrase,kind:'temporal',resolvedText:null,confidence:0,ambiguous:true,candidates:[]};const anchorDay=dayKey(anchor,timeZone);let targetStart:string|null=null,targetEnd:string|null=null;if(phrase.toLowerCase()==='yesterday'){targetStart=offsetCalendarDay(anchorDay,-1);targetEnd=targetStart}else if(phrase.toLowerCase()==='today'){targetStart=anchorDay;targetEnd=anchorDay}else if(phrase.toLowerCase()==='last week'){const currentDate=new Date(`${anchorDay}T00:00:00Z`);const dayOfWeek=currentDate.getUTCDay();const mondayOffset=dayOfWeek===0?6:dayOfWeek-1;const thisMonday=offsetCalendarDay(anchorDay,-mondayOffset);targetEnd=thisMonday?offsetCalendarDay(thisMonday,-1):null;targetStart=targetEnd?offsetCalendarDay(targetEnd,-6):null}else if(/two\s+days?\s+ago/i.test(phrase)){targetStart=offsetCalendarDay(anchorDay,-2);targetEnd=targetStart}else return null;if(!targetStart||!targetEnd)return{phrase,kind:'temporal',resolvedText:null,confidence:0,ambiguous:true,candidates:[]};const CONFIRMATION_RE=/^(?:yes|agreed|correct|exactly|right|confirmed)\b/i;const inWindow=rows.filter((row)=>row.role==='user'||row.role==='assistant').filter((row)=>{const key=dayKey(timestamp(row.createdAt),timeZone);return key>=targetStart!&&key<=targetEnd!});const confirmation=[...inWindow].reverse().find((row)=>CONFIRMATION_RE.test(row.content.trim())||/\b(?:decided|decision|agreed|selected|going\s+with|prioriti[sz]e)\b/i.test(row.content));const matches=confirmation?[confirmation,...inWindow.filter((row)=>row!==confirmation)]:[...inWindow].sort((a,b)=>timestamp(a.createdAt)-timestamp(b.createdAt));const best=matches[0];if(!best)return{phrase,kind:'temporal',resolvedText:null,confidence:0,ambiguous:true,candidates:[]};const candidates=matches.slice(0,5).map((row,index)=>({text:row.content,sourceRole:row.role as'user'|'assistant',sourceTimestamp:timestamp(row.createdAt),score:0.96-index*0.03,reasons:['calendar-bound temporal window','recency within target window']}));return{phrase,kind:'temporal',resolvedText:best.content,confidence:candidates[0]?.score??0.96,sourceRole:best.role as'user'|'assistant',ambiguous:false,candidates}}
export function resolveActiveThread(message:string,threads:readonly ConversationThreadRecord[]):ReferenceResolution|null{if(!CONTINUE_PATTERN.test(message)&&!CURRENT_TOPIC_PATTERN.test(message))return null;const phrase=normalize(message.match(CURRENT_TOPIC_PATTERN)?.[0]??'continue');const candidates=threads.filter((thread)=>thread.status==='active'||thread.status==='paused').sort((a,b)=>b.lastTouchedAt-a.lastTouchedAt).slice(0,5);const best=candidates[0];if(!best)return{phrase,kind:'continuation',resolvedText:null,confidence:0,ambiguous:true,candidates:[]};const describe=(thread:ConversationThreadRecord):string=>{const objectivePart=thread.title===thread.currentObjective?thread.title:`${thread.title}: ${thread.currentObjective}`;return thread.lastAssistantReply&&thread.lastAssistantReply!==thread.currentObjective?`${objectivePart} ${thread.lastAssistantReply}`:objectivePart};const candidateRows:ReferenceCandidate[]=candidates.map((thread,index)=>({text:describe(thread),sourceRole:'user',sourceTimestamp:thread.lastTouchedAt,score:Math.max(0.55,0.97-index*0.08),reasons:[thread.status==='active'?'active thread':'paused thread',`lifecycle=${thread.status}`,`rank=${index+1}`]}));const margin=candidateRows.length>1?Math.round((candidateRows[0]!.score-candidateRows[1]!.score)*1e6)/1e6:1;const ambiguous=margin<0.08;return{phrase,kind:'continuation',resolvedText:ambiguous?null:describe(best),confidence:candidateRows[0]?.score??0.97,sourceRole:'user',ambiguous,candidates:candidateRows}}
function resolveRecentContextualAnchor(message:string,rows:readonly PersistedConversationRow[]):ReferenceResolution|null{if(!/\b(?:earlier|before|what\s+we\s+(?:said|did|decided)|originally)\b/i.test(message))return null;const pool=rows.filter((row)=>row.role==='user'||row.role==='assistant');const isOriginal=/\boriginally\b/i.test(message);const ordered=isOriginal?pool.slice(0,16):pool.slice(-16).reverse();const candidates=ordered.map((row,index)=>{const recency=Math.max(0,0.6-index*0.04);const substance=Math.min(0.3,row.content.length/500);const roleBoost=row.role==='assistant'?0.08:0;const foundingBonus=isOriginal&&index===0?0.5:0;return{row,score:recency+substance+roleBoost+foundingBonus}}).sort((a,b)=>b.score-a.score);const best=candidates[0];if(!best)return{phrase:detectedReference(message)??message,kind:'contextual',resolvedText:null,confidence:0,ambiguous:true,candidates:[]};return{phrase:detectedReference(message)??message,kind:'contextual',resolvedText:best.row.content,confidence:Math.min(0.94,Math.max(0.55,best.score)),sourceRole:best.row.role as'user'|'assistant',ambiguous:false,candidates:candidates.slice(0,5).map(({row,score})=>({text:row.content,sourceRole:row.role as'user'|'assistant',sourceTimestamp:timestamp(row.createdAt),score,reasons:['prior discourse anchor (excludes immediate context)']}))}}
function referentialEntities(text:string):string[]{return [...new Set((text.match(/\b(?:Agent007|CEO|Vercel|GitHub|OpenAI|Groq|Mistral|Cerebras|Cloudflare|OpenRouter|Memory|Revenue|Venture OS|Mission OS)\b/g)??[]).map(normalize))]}
export function resolveGeneralReference(message:string,rows:readonly PersistedConversationRow[],stateAnchor?:string):ReferenceResolution|null{const phrase=detectedReference(message);if(!phrase)return null;const kind=kindFor(message);const contextual=resolveRecentContextualAnchor(message,rows);if(contextual)return contextual;const nounPhraseMatch=message.match(NOUN_PHRASE_REFERENCE_PATTERN);const queryText=nounPhraseMatch?.[1]??message;if(!PRONOUN_PATTERN.test(message)&&!nounPhraseMatch)return{phrase,kind,resolvedText:stateAnchor??null,confidence:stateAnchor?0.52:0,ambiguous:true,candidates:stateAnchor?[{text:stateAnchor,sourceRole:'user',sourceTimestamp:0,score:0.52,reasons:['active conversation-state anchor']}]:[]};const anchors=rows.filter((row)=>row.role==='user'||row.role==='assistant').slice(-20).reverse();const msgEntities=new Set(referentialEntities(message));const candidates=anchors.map((row,index)=>{const recency=Math.max(0,1-index*0.045);const lexical=overlap(queryText,row.content);const strength=Math.min(1,row.content.trim().length/160);const entityBonus=msgEntities.size&&[...msgEntities].some((entity)=>row.content.includes(entity))?0.15:0;const roleBoost=row.role==='assistant'?0.06:0;const score=Math.min(1,0.45*recency+0.27*lexical+0.10*strength+entityBonus+roleBoost);return{text:row.content,sourceRole:row.role as'user'|'assistant',sourceTimestamp:timestamp(row.createdAt),score,reasons:[`recency=${recency.toFixed(2)}`,`lexical=${lexical.toFixed(2)}`,`substance=${strength.toFixed(2)}`,`role=${row.role}`,...(entityBonus?['shared entity']:[])]}}).sort((a,b)=>b.score-a.score).slice(0,5);const best=candidates[0],second=candidates[1];if(!best||best.score<0.48)return{phrase,kind,resolvedText:stateAnchor??null,confidence:stateAnchor?0.52:0,ambiguous:true,candidates};const margin=second?best.score-second.score:1;const ambiguous=second?(margin<0.04||best.score<0.50):false;return{phrase,kind,resolvedText:ambiguous?null:best.text,confidence:Math.min(0.98,best.score),sourceRole:ambiguous?undefined:best.sourceRole,ambiguous,candidates}}