import { db } from './db'
import { COMMERCIAL_CATEGORIES, type CommercialEvent, type CommercialWorkflow, type EventStatus, type WorkflowStatus } from './commercial-control-plane'

const workflowTransitions:Record<WorkflowStatus,readonly WorkflowStatus[]>={queued:['running','cancelled'],running:['waiting','succeeded','failed','cancelled'],waiting:['running','succeeded','failed','cancelled'],succeeded:[],failed:['queued','cancelled'],cancelled:[]}
const eventTransitions:Record<EventStatus,readonly EventStatus[]>={accepted:['processed','failed','ignored'],processed:[],failed:['accepted','ignored'],ignored:[]}
const key=(k:string,t:string,i:string)=>`${k}:${t}:${i}`

async function findWorkflow(tenantId:string,workflowId:string){const rows=await db.memory.findMany({where:{category:COMMERCIAL_CATEGORIES.workflow},take:5000});for(const row of rows){try{const value=JSON.parse(row.value) as CommercialWorkflow;if(value.tenantId===tenantId&&value.workflowId===workflowId)return{row,value}}catch{}}
return null}

export async function transitionCommercialWorkflow(input:{tenantId:string;workflowId:string;status:WorkflowStatus;output?:Record<string,unknown>|null;nextRunAt?:string|null;incrementRetry?:boolean}):Promise<CommercialWorkflow|null>{const found=await findWorkflow(input.tenantId,input.workflowId);if(!found)return null;if(!workflowTransitions[found.value.status].includes(input.status))throw new Error(`Workflow transition ${found.value.status} -> ${input.status} is not permitted.`);const retryCount=input.incrementRetry?found.value.retryCount+1:found.value.retryCount;if(retryCount>found.value.maxRetries)throw new Error('Workflow retry limit exceeded.');const updated={...found.value,status:input.status,retryCount,output:input.output===undefined?found.value.output:input.output,nextRunAt:input.nextRunAt===undefined?found.value.nextRunAt:input.nextRunAt,updatedAt:new Date().toISOString()};await db.memory.update({where:{id:found.row.id},data:{value:JSON.stringify(updated)}});return updated}

export async function transitionCommercialEvent(input:{tenantId:string;idempotencyKey:string;status:EventStatus}):Promise<CommercialEvent|null>{const row=await db.memory.findUnique({where:{key:key('event',input.tenantId,input.idempotencyKey)}});if(!row)return null;let event:CommercialEvent;try{event=JSON.parse(row.value) as CommercialEvent}catch{throw new Error('Commercial event record is corrupt.')};if(!eventTransitions[event.status].includes(input.status))throw new Error(`Event transition ${event.status} -> ${input.status} is not permitted.`);const updated={...event,status:input.status};await db.memory.update({where:{id:row.id},data:{value:JSON.stringify(updated)}});return updated}
export function validateCommercialLifecycleContracts():string[]{return Object.keys(workflowTransitions).length===6&&Object.keys(eventTransitions).length===4?[]:['Commercial lifecycle contract is incomplete.']}
