import {db} from './db'
import {getPortfolio} from './business-portfolio'
import {normalizeMetric,optimize} from './portfolio-intelligence-rules'
import {CEO_VENTURE_MANDATE} from './venture-mandate'
import type {PortfolioBusiness} from './portfolio-intelligence-contract'
import type {PortfolioMetric,PortfolioSnapshot,PortfolioDecisionRecord} from './portfolio-intelligence-types'
const json=(v:string)=>{try{return JSON.parse(v) as any}catch{return null}}
const business=(n:string):PortfolioBusiness=>{const s=n.toLowerCase();if(s.includes('revenue recovery'))return'revenue-recovery';if(s.includes('operations kit'))return'operations-kit';if(s.includes('career command'))return'career-command';throw new Error(`Unsupported venture: ${n}`)}
const evidence=async(b:PortfolioBusiness)=>{const rows=await db.memory.findMany({where:{category:'commercial_evidence'}});const hit=rows.filter(r=>json(r.value)?.business===b);const score=hit.length?hit.reduce((t,r)=>{const v=Number(json(r.value)?.confidence);return t+(Number.isFinite(v)?(v<=1?v*100:v):0)},0)/hit.length:0;return{confidence:Math.max(0,Math.min(100,score)),ids:[...new Set(hit.map(r=>r.key))]}}
const periods=async(b:PortfolioBusiness,currentPeriod:string)=>{const rows=await db.memory.findMany({where:{category:'portfolio_intelligence_snapshot'}});const seen=new Set<string>();for(const row of rows){const snapshot=json(row.value) as PortfolioSnapshot|null;if(!snapshot)continue;for(const metric of snapshot.metrics)if(metric.business===b&&metric.period)seen.add(metric.period)}return seen.has(currentPeriod)?seen.size:seen.size+1}
export async function buildPortfolioSnapshot():Promise<PortfolioSnapshot>{const raw=await getPortfolio() as any[];const active=raw.filter(x=>x&&x.lifecycle!=='retired'&&typeof x.name==='string');const currentPeriod=new Date().toISOString().slice(0,10);const metrics:PortfolioMetric[]=await Promise.all(active.map(async x=>{const b=business(x.name);const [e,p]=await Promise.all([evidence(b),periods(b,currentPeriod)]);const confidence=e.confidence/100>=CEO_VENTURE_MANDATE.validationConfidenceMinimum?e.confidence:0;return normalizeMetric({business:b,revenue:Number(x.monthlyRevenue)||0,cost:Number(x.monthlyCost)||0,customers:Number(x.customerCount)||0,leads:null,conversions:null,automation:Number.isFinite(x.automationLevel)?x.automationLevel:null,satisfaction:null,confidence,observedPeriods:p,evidenceIds:e.ids,source:'portfolio+commercial-evidence',period:currentPeriod})}));const revenue=metrics.reduce((s,m)=>s+m.revenue,0);const cost=metrics.reduce((s,m)=>s+m.cost,0);const customers=metrics.reduce((s,m)=>s+m.customers,0);const margin=revenue?((revenue-cost)/revenue)*100:0;const health=metrics.length?Math.round(metrics.reduce((s,m)=>s+optimize(m).score,0)/metrics.length):0;const snapshot={snapshotId:`portfolio_snapshot_${Date.now()}`,createdAt:new Date().toISOString(),metrics,revenue,cost,netRevenue:revenue-cost,margin,customers,health};await db.memory.create({data:{key:snapshot.snapshotId,category:'portfolio_intelligence_snapshot',value:JSON.stringify(snapshot)}});return snapshot}
export async function createOptimizationRecords(snapshot:PortfolioSnapshot):Promise<PortfolioDecisionRecord[]>{return Promise.all(snapshot.metrics.map(async m=>{const r=optimize(m);const out={...r,decisionId:`portfolio_decision_${m.business}_${Date.now()}`,snapshotId:snapshot.snapshotId,createdAt:new Date().toISOString(),status:'recommended' as const};await db.memory.create({data:{key:out.decisionId,category:'portfolio_intelligence_decision',value:JSON.stringify(out)}});return out}))}
export async function runPortfolioOptimization(){const snapshot=await buildPortfolioSnapshot();return{snapshot,decisions:await createOptimizationRecords(snapshot)}}
export async function getPortfolioOptimizationHistory(limit=25):Promise<PortfolioDecisionRecord[]>{const rows=await db.memory.findMany({where:{category:'portfolio_intelligence_decision'},orderBy:{createdAt:'desc'},take:Math.max(1,Math.min(100,limit))});return rows.map(r=>json(r.value)).filter(Boolean) as PortfolioDecisionRecord[]}
