import {db} from './db'
import {getPortfolio} from './business-portfolio'
import {normalizeMetric,optimize} from './portfolio-intelligence-rules'
import type {PortfolioBusiness} from './portfolio-intelligence-contract'
import type {PortfolioMetric,PortfolioSnapshot,PortfolioDecisionRecord} from './portfolio-intelligence-types'
const parse=(v:string)=>{try{return JSON.parse(v) as any}catch{return null}}
const business=(name:string):PortfolioBusiness=>{const n=name.toLowerCase();if(n.includes('revenue recovery'))return'revenue-recovery';if(n.includes('operations kit'))return'operations-kit';if(n.includes('career command'))return'career-command';throw new Error(`Unsupported venture: ${name}`)}
export async function buildPortfolioSnapshot():Promise<PortfolioSnapshot>{const raw=await getPortfolio() as Array<any>;const active=raw.filter(x=>x&&x.lifecycle!=='retired'&&typeof x.name==='string');const metrics:PortfolioMetric[]=active.map(x=>normalizeMetric({business:business(x.name),revenue:Number(x.monthlyRevenue)||0,cost:Number(x.monthlyCost)||0,customers:Number(x.customerCount)||0,leads:null,conversions:null,automation:Number.isFinite(x.automationLevel)?x.automationLevel:null,satisfaction:null,confidence:0,observedPeriods:1,evidenceIds:[],source:'portfolio',period:new Date().toISOString().slice(0,10)}));const revenue=metrics.reduce((s,x)=>s+x.revenue,0),cost=metrics.reduce((s,x)=>s+x.cost,0),customers=metrics.reduce((s,x)=>s+x.customers,0),margin=revenue?((revenue-cost)/revenue)*100:0,health=metrics.length?Math.round(metrics.reduce((s,x)=>s+optimize(x).score,0)/metrics.length):0;const snapshot={snapshotId:`portfolio_snapshot_${Date.now()}`,createdAt:new Date().toISOString(),metrics,revenue,cost,netRevenue:revenue-cost,margin,customers,health};await db.memory.create({data:{key:snapshot.snapshotId,category:'portfolio_intelligence_snapshot',value:JSON.stringify(snapshot)}});return snapshot}
export async function createOptimizationRecords(snapshot:PortfolioSnapshot):Promise<PortfolioDecisionRecord[]>{return Promise.all(snapshot.metrics.map(async m=>{const r=optimize(m);const record={...r,decisionId:`portfolio_decision_${m.business}_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,snapshotId:snapshot.snapshotId,createdAt:new Date().toISOString(),status:'recommended' as const};await db.memory.create({data:{key:record.decisionId,category:'portfolio_intelligence_decision',value:JSON.stringify(record)}});return record}))}
export async function runPortfolioOptimization(){const snapshot=await buildPortfolioSnapshot();return{snapshot,decisions:await createOptimizationRecords(snapshot)}}
export async function getPortfolioOptimizationHistory(limit=25):Promise<PortfolioDecisionRecord[]>{const rows=await db.memory.findMany({where:{category:'portfolio_intelligence_decision'},orderBy:{createdAt:'desc'},take:Math.max(1,Math.min(100,limit))});return rows.map(x=>parse(x.value)).filter(Boolean) as PortfolioDecisionRecord[]}
