import { db } from './db'
import type { FunnelSnapshot, FunnelSnapshotInput } from './revenue-recovery-contract'
function count(v:number){return Number.isFinite(v)?Math.max(0,Math.floor(v)):0}
function money(v:number){return Number.isFinite(v)?Math.max(0,v):0}
function rate(n:number,d:number){return d>0?Math.max(0,Math.min(1,n/d)):0}
function clean(v:string){return v.trim().replace(/\s+/g,' ')}
export function buildFunnelSnapshot(input:FunnelSnapshotInput):FunnelSnapshot{if(!clean(input.tenantId)||!clean(input.customerId)||!clean(input.source))throw new Error('tenantId, customerId and source are required.');const leads=count(input.leadCount),contacted=count(input.contactedCount),booked=count(input.bookedCount),shows=count(input.showCount),noShows=count(input.noShowCount),won=count(input.wonCount);if(contacted>leads||booked>contacted||shows>booked||noShows>booked||won>shows)throw new Error('Funnel counts violate stage ordering.');if(leads>0&&money(input.averageTransactionValue)<=0)throw new Error('averageTransactionValue must be positive when leads exist.');const confidence=Math.round((.55*Math.min(1,leads/30)+.3*(clean(input.source).length>=4?1:0)+.15*(leads>0?1:.2))*100)/100;return{...input,tenantId:clean(input.tenantId),customerId:clean(input.customerId),source:clean(input.source),leadCount:leads,contactedCount:contacted,bookedCount:booked,showCount:shows,noShowCount:noShows,wonCount:won,staleOpportunityCount:count(input.staleOpportunityCount),missedCallCount:count(input.missedCallCount),averageTransactionValue:money(input.averageTransactionValue),averageResponseMinutes:input.averageResponseMinutes!==null&&Number.isFinite(input.averageResponseMinutes)?input.averageResponseMinutes:null,grossMarginPercent:input.grossMarginPercent!==null&&Number.isFinite(input.grossMarginPercent)?input.grossMarginPercent:null,snapshotId:`rrs_${Buffer.from(`${input.tenantId}:${input.customerId}:${input.observedAt}`).toString('base64url')}`,contactRate:rate(contacted,leads),bookingRateAmongContacted:rate(booked,contacted),showRateAmongBooked:rate(shows,booked),closeRateAmongShows:rate(won,shows),confidence,createdAt:new Date().toISOString()}}
export async function persistFunnelSnapshot(snapshot:FunnelSnapshot){const key=`revenue_recovery_snapshot:${snapshot.tenantId}:${snapshot.customerId}:${snapshot.observedAt}`;const existing=await db.memory.findUnique({where:{key}});if(existing)return{created:false,snapshot:JSON.parse(existing.value) as FunnelSnapshot};await db.memory.create({data:{key,category:'revenue_recovery_snapshot',value:JSON.stringify(snapshot)}});return{created:true,snapshot}}
export async function getLatestFunnelSnapshot(tenantId:string,customerId:string){const records=await db.memory.findMany({where:{category:'revenue_recovery_snapshot'},orderBy:{createdAt:'desc'},take:1000});for(const record of records){try{const snapshot=JSON.parse(record.value) as FunnelSnapshot;if(snapshot.tenantId===tenantId&&snapshot.customerId===customerId)return snapshot}catch{} }return null}
