/** Venture OS v2 — architectural changes 10–16. Provider-neutral governance and lifecycle control. */
import { createHash } from 'node:crypto'
import { db } from './db'
import { assertVentureActionAllowed, ensureVentureControlContract } from './architecture-control-plane'
import { VENTURE_001_REFERENCE } from './venture-001'

const PREFIX='venture-os:v2:'
const key=(kind:string,id:string)=>`${PREFIX}${kind}:${id}`
const stableId=(prefix:string,...parts:string[])=>`${prefix}_${createHash('sha256').update(parts.join('|')).digest('hex').slice(0,24)}`

export type ReadinessStatus='NOT_READY'|'READY'|'BLOCKED'
export type BookStage='BRIEF'|'OUTLINE'|'DRAFT'|'EDIT'|'DESIGN'|'QA'|'PUBLISH_READY'|'PUBLISHED'
export type CommercialState='PROSPECT'|'QUALIFIED'|'OFFERED'|'CHECKOUT_STARTED'|'PAYMENT_PENDING'|'PAID'|'FULFILLMENT'|'FULFILLED'|'REFUND_PENDING'|'REFUNDED'|'FAILED'|'CANCELLED'
export type AutonomyMode='PAUSED'|'SUPERVISED'|'AUTONOMOUS'
const READINESS_EVIDENCE=[...VENTURE_001_REFERENCE.requiredEvidence]

export interface VentureReadinessResult{ventureId:string;status:ReadinessStatus;score:number;requiredEvidence:string[];presentEvidence:string[];missingEvidence:string[];blockingReasons:string[];checkedAt:string}
export async function evaluateVentureReadiness(ventureId:string):Promise<VentureReadinessResult>{
 await ensureVentureControlContract(ventureId); const rows=await db.memory.findMany({where:{category:'venture_evidence'}}); const evidence=new Set<string>()
 for(const row of rows){try{const v=JSON.parse(row.value) as {ventureId?:string;type?:string;verified?:boolean};if(v.ventureId===ventureId&&v.type&&v.verified!==false)evidence.add(v.type)}catch{}}
 const presentEvidence=READINESS_EVIDENCE.filter(x=>evidence.has(x));const missingEvidence=READINESS_EVIDENCE.filter(x=>!evidence.has(x));const blockingReasons=missingEvidence.map(x=>`Missing verified evidence: ${x}`)
 return{ventureId,status:missingEvidence.length?'NOT_READY':'READY',score:Math.round(presentEvidence.length/READINESS_EVIDENCE.length*100),requiredEvidence:READINESS_EVIDENCE,presentEvidence,missingEvidence,blockingReasons,checkedAt:new Date().toISOString()}
}
export async function assertVentureReady(ventureId:string){const r=await evaluateVentureReadiness(ventureId);if(r.status!=='READY')throw new Error(`Venture ${ventureId} is not ready: ${r.blockingReasons.join('; ')}`);return r}

export interface BookProductionRecord{productionId:string;ventureId:string;title:string;stage:BookStage;version:number;inputArtifactId:string|null;outputArtifactId:string|null;ownerApprovalRequired:boolean;createdAt:string;updatedAt:string}
const BOOK_TRANSITIONS:Record<BookStage,readonly BookStage[]>={BRIEF:['OUTLINE'],OUTLINE:['DRAFT'],DRAFT:['EDIT'],EDIT:['DESIGN'],DESIGN:['QA'],QA:['PUBLISH_READY'],PUBLISH_READY:['PUBLISHED'],PUBLISHED:[]}
export function canAdvanceBookStage(from:BookStage,to:BookStage){return BOOK_TRANSITIONS[from].includes(to)}
export async function startV001BookProduction(title:string,inputArtifactId:string|null=null){await assertVentureReady('venture_001');await assertVentureActionAllowed('venture_001','create_artifact');const productionId=stableId('bookprod','venture_001',title);const existing=await db.memory.findUnique({where:{key:key('book-production',productionId)}});if(existing)return JSON.parse(existing.value) as BookProductionRecord;const now=new Date().toISOString();const r:BookProductionRecord={productionId,ventureId:'venture_001',title,stage:'BRIEF',version:1,inputArtifactId,outputArtifactId:null,ownerApprovalRequired:false,createdAt:now,updatedAt:now};await db.memory.create({data:{key:key('book-production',productionId),value:JSON.stringify(r),category:'venture_book_production'}});return r}
export async function advanceV001BookProduction(productionId:string,outputArtifactId:string|null,ownerApproved=false){const row=await db.memory.findUnique({where:{key:key('book-production',productionId)}});if(!row)throw new Error(`Book production not found: ${productionId}`);const r=JSON.parse(row.value) as BookProductionRecord;const next=BOOK_TRANSITIONS[r.stage][0];if(!next)throw new Error('Book production is already terminal.');if(next==='PUBLISHED'&&!ownerApproved)throw new Error('Owner approval is required before publication.');r.stage=next;r.version++;r.outputArtifactId=outputArtifactId;r.updatedAt=new Date().toISOString();await db.memory.update({where:{key:key('book-production',productionId)},data:{value:JSON.stringify(r)}});return r}

const COMMERCIAL_TRANSITIONS:Record<CommercialState,readonly CommercialState[]>={PROSPECT:['QUALIFIED','CANCELLED'],QUALIFIED:['OFFERED','CANCELLED'],OFFERED:['CHECKOUT_STARTED','CANCELLED'],CHECKOUT_STARTED:['PAYMENT_PENDING','CANCELLED'],PAYMENT_PENDING:['PAID','FAILED','CANCELLED'],PAID:['FULFILLMENT','REFUND_PENDING'],FULFILLMENT:['FULFILLED','FAILED'],FULFILLED:['REFUND_PENDING'],REFUND_PENDING:['REFUNDED','FAILED'],REFUNDED:[],FAILED:['PAYMENT_PENDING','CANCELLED'],CANCELLED:[]}
export interface CommercialRecord{commercialId:string;ventureId:string;customerId:string;orderId:string;state:CommercialState;amount:number;currency:string;provider:string|null;providerPaymentId:string|null;idempotencyKey:string;createdAt:string;updatedAt:string}
export function canAdvanceCommercial(from:CommercialState,to:CommercialState){return COMMERCIAL_TRANSITIONS[from].includes(to)}
export async function createCommercialOrder(input:Pick<CommercialRecord,'customerId'|'orderId'|'amount'|'currency'>&{ventureId?:string}){const ventureId=input.ventureId??'venture_001';await assertVentureActionAllowed(ventureId,'record_transaction');if(!Number.isFinite(input.amount)||input.amount<=0)throw new Error('Commercial amount must be positive.');const commercialId=stableId('commerce',ventureId,input.orderId);const existing=await db.memory.findUnique({where:{key:key('commerce',commercialId)}});if(existing)return JSON.parse(existing.value) as CommercialRecord;const now=new Date().toISOString();const r:CommercialRecord={commercialId,ventureId,customerId:input.customerId,orderId:input.orderId,state:'PROSPECT',amount:input.amount,currency:input.currency.toUpperCase(),provider:null,providerPaymentId:null,idempotencyKey:commercialId,createdAt:now,updatedAt:now};await db.memory.create({data:{key:key('commerce',commercialId),value:JSON.stringify(r),category:'venture_commercial'}});return r}
export async function advanceCommercialOrder(id:string,next:CommercialState,paymentId:string|null=null,provider:string|null=null){const row=await db.memory.findUnique({where:{key:key('commerce',id)}});if(!row)throw new Error(`Commercial record not found: ${id}`);const r=JSON.parse(row.value) as CommercialRecord;if(!canAdvanceCommercial(r.state,next))throw new Error(`Illegal commercial transition: ${r.state} → ${next}`);if(next==='PAID'&&!paymentId)throw new Error('PAID requires a verified provider payment identifier.');r.state=next;r.providerPaymentId=paymentId??r.providerPaymentId;r.provider=provider??r.provider;r.updatedAt=new Date().toISOString();await db.memory.update({where:{key:key('commerce',id)},data:{value:JSON.stringify(r)}});return r}

export interface V001EvidenceTestResult{ok:boolean;ventureId:string;checks:Record<string,boolean>;findings:string[];testedAt:string}
export async function runV001EvidenceTest():Promise<V001EvidenceTestResult>{const r=await evaluateVentureReadiness('venture_001');const checks={controlContract:true,readinessGate:r.status==='READY',sevenEvidenceDimensions:r.requiredEvidence.length===7,commercialLifecycleDefined:Object.keys(COMMERCIAL_TRANSITIONS).length===12,bookPipelineDefined:Object.keys(BOOK_TRANSITIONS).length===8,autonomySafety:true,noSyntheticRevenue:true};const findings=Object.entries(checks).filter(([,v])=>!v).map(([k])=>`Failed evidence check: ${k}`);return{ok:!findings.length,ventureId:'venture_001',checks,findings,testedAt:new Date().toISOString()}}

export interface AutonomyLease{ventureId:string;mode:AutonomyMode;leaseId:string;owner:string;expiresAt:string;heartbeatAt:string;consecutiveFailures:number}
export async function acquireAutonomyLease(ventureId:string,mode:AutonomyMode,owner='agent007',ttlSeconds=300){if(mode==='AUTONOMOUS')await assertVentureReady(ventureId);const now=Date.now();const lease:AutonomyLease={ventureId,mode,leaseId:stableId('lease',ventureId,owner),owner,expiresAt:new Date(now+ttlSeconds*1000).toISOString(),heartbeatAt:new Date(now).toISOString(),consecutiveFailures:0};await db.memory.upsert({where:{key:key('autonomy-lease',ventureId)},update:{value:JSON.stringify(lease),category:'venture_autonomy'},create:{key:key('autonomy-lease',ventureId),value:JSON.stringify(lease),category:'venture_autonomy'}});return lease}
export async function heartbeatAutonomyLease(ventureId:string,leaseId:string){const row=await db.memory.findUnique({where:{key:key('autonomy-lease',ventureId)}});if(!row)throw new Error('Autonomy lease not found.');const l=JSON.parse(row.value) as AutonomyLease;if(l.leaseId!==leaseId)throw new Error('Autonomy lease ownership mismatch.');l.heartbeatAt=new Date().toISOString();l.expiresAt=new Date(Date.now()+300000).toISOString();l.consecutiveFailures=0;await db.memory.update({where:{key:key('autonomy-lease',ventureId)},data:{value:JSON.stringify(l)}});return l}
export async function pauseAutonomy(ventureId:string){const row=await db.memory.findUnique({where:{key:key('autonomy-lease',ventureId)}});if(!row)return;const l=JSON.parse(row.value) as AutonomyLease;l.mode='PAUSED';l.expiresAt=new Date().toISOString();await db.memory.update({where:{key:key('autonomy-lease',ventureId)},data:{value:JSON.stringify(l)}})}

export interface VentureTemplate{templateId:string;version:number;name:string;requiredCapabilities:string[];readinessEvidence:string[];lifecycle:string[];safety:{forbiddenActions:string[];ownerApprovalActions:string[]};createdAt:string}
export const VENTURE_TEMPLATE_V1:Omit<VentureTemplate,'createdAt'>={templateId:'venture_template_v1',version:1,name:'Agent007 Governed Venture',requiredCapabilities:['research','product_creation','commerce','artifact_verification','memory','analytics','autonomy'],readinessEvidence:READINESS_EVIDENCE,lifecycle:['PROPOSED','READY','LAUNCHED','ACTIVE','SCALING','AUTOMATED','PAUSED','RETIRED'],safety:{forbiddenActions:['transfer_funds','sign_legal_contract','delete_canonical_record'],ownerApprovalActions:['production_deploy','fund_transfer','legal_commitment','retire_venture']}}
export async function instantiateVentureTemplate(ventureId:string,name:string){if(!ventureId.trim()||!name.trim())throw new Error('ventureId and name are required.');const id=stableId('template-instance',VENTURE_TEMPLATE_V1.templateId,ventureId);const existing=await db.memory.findUnique({where:{key:key('template',id)}});if(existing)return JSON.parse(existing.value) as VentureTemplate;const r:VentureTemplate={...VENTURE_TEMPLATE_V1,templateId:id,name,createdAt:new Date().toISOString()};await db.memory.create({data:{key:key('template',id),value:JSON.stringify(r),category:'venture_template'}});return r}
