/** Venture OS v2 — architectural changes 10–16. */
import { createHash } from 'node:crypto'
import { db } from './db'
import { assertVentureActionAllowed, ensureVentureControlContract, registerArtifact, verifyArtifact } from './architecture-control-plane'
import { VENTURE_001_REFERENCE } from './venture-001'
import { COMMERCIAL_CATEGORIES, createCommercialWorkflow, ensureCommercialTenant, getCommercialWorkflows, recordCommercialEvent, transitionCommercialWorkflow, type BillingRecord, type Entitlement } from './commercial-control-plane'

const PREFIX='venture-os:v2:'
const key=(kind:string,id:string)=>`${PREFIX}${kind}:${id}`
const stableId=(prefix:string,...parts:string[])=>`${prefix}_${createHash('sha256').update(parts.join('|')).digest('hex').slice(0,24)}`
const READINESS_EVIDENCE=[...VENTURE_001_REFERENCE.requiredEvidence]

export type ReadinessStatus='NOT_READY'|'READY'|'BLOCKED'
export type BookStage='BRIEF'|'OUTLINE'|'DRAFT'|'EDIT'|'DESIGN'|'QA'|'PUBLISH_READY'|'PUBLISHED'
export type CommercialState='PROSPECT'|'QUALIFIED'|'OFFERED'|'CHECKOUT_STARTED'|'PAYMENT_PENDING'|'PAID'|'FULFILLMENT'|'FULFILLED'|'REFUND_PENDING'|'REFUNDED'|'FAILED'|'CANCELLED'
export type AutonomyMode='PAUSED'|'SUPERVISED'|'AUTONOMOUS'

export interface VentureReadinessResult{ventureId:string;status:ReadinessStatus;score:number;requiredEvidence:string[];presentEvidence:string[];missingEvidence:string[];blockingReasons:string[];checkedAt:string}
export async function evaluateVentureReadiness(ventureId:string):Promise<VentureReadinessResult>{await ensureVentureControlContract(ventureId);const rows=await db.memory.findMany({where:{category:'venture_evidence'}});const evidence=new Set<string>();for(const row of rows){try{const value=JSON.parse(row.value) as {ventureId?:string;type?:string;verified?:boolean};if(value.ventureId===ventureId&&value.type&&value.verified!==false)evidence.add(value.type)}catch{}}const presentEvidence=READINESS_EVIDENCE.filter((item)=>evidence.has(item));const missingEvidence=READINESS_EVIDENCE.filter((item)=>!evidence.has(item));return{ventureId,status:missingEvidence.length===0?'READY':'NOT_READY',score:Math.round((presentEvidence.length/READINESS_EVIDENCE.length)*100),requiredEvidence:READINESS_EVIDENCE,presentEvidence,missingEvidence,blockingReasons:missingEvidence.map((item)=>`Missing verified evidence: ${item}`),checkedAt:new Date().toISOString()}}
export async function assertVentureReady(ventureId:string){const result=await evaluateVentureReadiness(ventureId);if(result.status!=='READY')throw new Error(`Venture ${ventureId} is not ready: ${result.blockingReasons.join('; ')}`);return result}

export interface BookProductionRecord{productionId:string;ventureId:string;title:string;stage:BookStage;version:number;chapterCount:number;targetPageMin:number;targetPageMax:number;chapters:string[];inputArtifactId:string|null;outputArtifactId:string|null;ownerApprovalRequired:boolean;createdAt:string;updatedAt:string}
const BOOK_TRANSITIONS:Record<BookStage,readonly BookStage[]>={BRIEF:['OUTLINE'],OUTLINE:['DRAFT'],DRAFT:['EDIT'],EDIT:['DESIGN'],DESIGN:['QA'],QA:['PUBLISH_READY'],PUBLISH_READY:['PUBLISHED'],PUBLISHED:[]}
export function canAdvanceBookStage(from:BookStage,to:BookStage){return BOOK_TRANSITIONS[from].includes(to)}
export function validateV001BookSpecification(input:{chapterCount:number;pageCount:number;chapters?:string[]}):string[]{const issues:string[]=[];if(input.chapterCount!==7)issues.push('V001 requires exactly 7 chapters.');if(input.pageCount<25||input.pageCount>30)issues.push('V001 requires 25–30 Letter pages.');if(input.chapters&&input.chapters.length!==7)issues.push('V001 chapter manifest must contain exactly 7 entries.');if(input.chapters&&new Set(input.chapters.map((item)=>item.trim().toLowerCase())).size!==input.chapters.length)issues.push('V001 chapter manifest contains duplicates.');return issues}
export async function startV001BookProduction(title:string,inputArtifactId:string|null=null,chapters:string[]=[]):Promise<BookProductionRecord>{await assertVentureReady('venture_001');await assertVentureActionAllowed('venture_001','create_artifact');const issues=validateV001BookSpecification({chapterCount:chapters.length,pageCount:25,chapters});if(issues.length)throw new Error(`V001 specification invalid: ${issues.join(' | ')}`);const productionId=stableId('bookprod','venture_001',title);const existing=await db.memory.findUnique({where:{key:key('book-production',productionId)}});if(existing)return JSON.parse(existing.value) as BookProductionRecord;const now=new Date().toISOString();const record:BookProductionRecord={productionId,ventureId:'venture_001',title,stage:'BRIEF',version:1,chapterCount:7,targetPageMin:25,targetPageMax:30,chapters:[...chapters],inputArtifactId,outputArtifactId:null,ownerApprovalRequired:false,createdAt:now,updatedAt:now};await db.memory.create({data:{key:key('book-production',productionId),value:JSON.stringify(record),category:'venture_book_production'}});return record}
export async function advanceV001BookProduction(productionId:string,outputArtifactId:string|null,ownerApproved=false):Promise<BookProductionRecord>{const row=await db.memory.findUnique({where:{key:key('book-production',productionId)}});if(!row)throw new Error(`Book production not found: ${productionId}`);const record=JSON.parse(row.value) as BookProductionRecord;const next=BOOK_TRANSITIONS[record.stage][0];if(!next)throw new Error('Book production is already terminal.');if(next==='PUBLISH_READY'||next==='PUBLISHED'){const issues=validateV001BookSpecification({chapterCount:record.chapterCount,pageCount:record.targetPageMin,chapters:record.chapters});if(issues.length)throw new Error(`V001 release gate failed: ${issues.join(' | ')}`);if(!outputArtifactId)throw new Error('Canonical output artifact required at release stages.')}if(next==='PUBLISHED'&&!ownerApproved)throw new Error('Owner approval is required before publication.');if(record.outputArtifactId&&next!=='PUBLISHED')await verifyArtifact(record.outputArtifactId,'venture_os','V001 production transition');record.stage=next;record.version++;record.outputArtifactId=outputArtifactId;record.updatedAt=new Date().toISOString();await db.memory.update({where:{key:key('book-production',productionId)},data:{value:JSON.stringify(record)}});return record}

export interface CommercialRecord{commercialId:string;ventureId:string;customerId:string;orderId:string;state:CommercialState;amount:number;currency:string;provider:string|null;providerPaymentId:string|null;idempotencyKey:string;tenantId:string;workflowId:string;createdAt:string;updatedAt:string}
const COMMERCIAL_TRANSITIONS:Record<CommercialState,readonly CommercialState[]>={PROSPECT:['QUALIFIED','CANCELLED'],QUALIFIED:['OFFERED','CANCELLED'],OFFERED:['CHECKOUT_STARTED','CANCELLED'],CHECKOUT_STARTED:['PAYMENT_PENDING','CANCELLED'],PAYMENT_PENDING:['PAID','FAILED','CANCELLED'],PAID:['FULFILLMENT','REFUND_PENDING'],FULFILLMENT:['FULFILLED','FAILED'],FULFILLED:['REFUND_PENDING'],REFUND_PENDING:['REFUNDED','FAILED'],REFUNDED:[],FAILED:['PAYMENT_PENDING','CANCELLED'],CANCELLED:[]}
export function canAdvanceCommercial(from:CommercialState,to:CommercialState){return COMMERCIAL_TRANSITIONS[from].includes(to)}
const TENANT_ID='tenant_venture_001'
async function writeBilling(tenantId:string,commercialId:string,ventureId:string,customerId:string,amount:number,currency:string,status:BillingRecord['status'],provider:string|null,paymentId:string|null){const record:BillingRecord={billingId:commercialId,tenantId,business:'shared-platform',provider:provider??'unverified',providerObjectId:paymentId,customerId,amount,currency,status,product:`${ventureId}:book`,idempotencyKey:commercialId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const recordKey=`commercial_billing:${tenantId}:${commercialId}`;await db.memory.upsert({where:{key:recordKey},update:{value:JSON.stringify(record),category:COMMERCIAL_CATEGORIES.billing},create:{key:recordKey,category:COMMERCIAL_CATEGORIES.billing,value:JSON.stringify(record)}})}
async function writeEntitlement(tenantId:string,commercialId:string,ventureId:string,customerId:string,status:Entitlement['status']){const entitlement:Entitlement={entitlementId:stableId('entitlement',commercialId),tenantId,business:'shared-platform',product:`${ventureId}:book`,subjectId:customerId,status,limits:{},validUntil:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const recordKey=`commercial_entitlement:${tenantId}:${commercialId}`;await db.memory.upsert({where:{key:recordKey},update:{value:JSON.stringify(entitlement),category:COMMERCIAL_CATEGORIES.entitlement},create:{key:recordKey,category:COMMERCIAL_CATEGORIES.entitlement,value:JSON.stringify(entitlement)}})}
export async function createCommercialOrder(input:Pick<CommercialRecord,'customerId'|'orderId'|'amount'|'currency'>&{ventureId?:string;tenantId?:string}):Promise<CommercialRecord>{const ventureId=input.ventureId??'venture_001';const tenantId=input.tenantId??TENANT_ID;await ensureVentureControlContract(ventureId);if(!Number.isFinite(input.amount)||input.amount<=0)throw new Error('Commercial amount must be positive.');await ensureCommercialTenant('venture_001','Venture 001 Commercial Tenant');const commercialId=stableId('commerce',ventureId,input.orderId);const workflows=await getCommercialWorkflows(tenantId);const existing=workflows.find((item)=>item.workflowId===commercialId);if(existing){const data=existing.input as Partial<CommercialRecord>;return{...data,commercialId,tenantId,workflowId:existing.workflowId,state:(existing.output?.lifecycleState??data.state??'PROSPECT') as CommercialState} as CommercialRecord}const workflow=await createCommercialWorkflow({tenantId,business:'shared-platform',workflowType:'venture_order',status:'queued',input:{ventureId,customerId:input.customerId,orderId:input.orderId,amount:input.amount,currency:input.currency.toUpperCase(),state:'PROSPECT',provider:null,providerPaymentId:null},maxRetries:5,nextRunAt:new Date().toISOString(),idempotencyKey:commercialId});const now=new Date().toISOString();return{commercialId,ventureId,customerId:input.customerId,orderId:input.orderId,state:'PROSPECT',amount:input.amount,currency:input.currency.toUpperCase(),provider:null,providerPaymentId:null,idempotencyKey:commercialId,tenantId,workflowId:workflow.workflow.workflowId,createdAt:now,updatedAt:now}}
export async function advanceCommercialOrder(commercialId:string,next:CommercialState,paymentId:string|null=null,provider:string|null=null):Promise<CommercialRecord>{const workflows=await getCommercialWorkflows(TENANT_ID);const current=workflows.find((item)=>item.workflowId===commercialId);if(!current)throw new Error(`Commercial order not found: ${commercialId}`);const data=current.input as Partial<CommercialRecord>;const from=(current.output?.lifecycleState??data.state??'PROSPECT') as CommercialState;if(!canAdvanceCommercial(from,next))throw new Error(`Illegal commercial transition: ${from} → ${next}`);if(next==='PAID'&&!paymentId)throw new Error('PAID requires a verified provider payment identifier.');const terminal=next==='FULFILLED'||next==='REFUNDED'||next==='CANCELLED'||next==='FAILED';await transitionCommercialWorkflow({tenantId:TENANT_ID,workflowId:current.workflowId,status:terminal?'succeeded':'running',output:{...(current.output??{}),lifecycleState:next,provider,paymentId},nextRunAt:terminal?null:new Date().toISOString()});await recordCommercialEvent({tenantId:TENANT_ID,business:'shared-platform',type:'venture_order_transition',source:'venture_os',entityType:'venture_order',entityId:commercialId,payload:{from,to:next,provider,paymentId},occurredAt:new Date().toISOString(),idempotencyKey:stableId('commerce-event',commercialId,from,next,paymentId??'')});const ventureId=String(data.ventureId??'venture_001');const customerId=String(data.customerId??'');const amount=Number(data.amount??0);const currency=String(data.currency??'USD');if(next==='PAID')await writeBilling(TENANT_ID,commercialId,ventureId,customerId,amount,currency,'paid',provider,paymentId);if(next==='FAILED')await writeBilling(TENANT_ID,commercialId,ventureId,customerId,amount,currency,'failed',provider,paymentId);if(next==='REFUNDED')await writeBilling(TENANT_ID,commercialId,ventureId,customerId,amount,currency,'refunded',provider,paymentId);if(next==='FULFILLMENT'||next==='FULFILLED')await writeEntitlement(TENANT_ID,commercialId,ventureId,customerId,'active');if(next==='REFUNDED'||next==='CANCELLED')await writeEntitlement(TENANT_ID,commercialId,ventureId,customerId,'revoked');const now=new Date().toISOString();return{...data,commercialId,tenantId:TENANT_ID,workflowId:current.workflowId,state:next,provider:provider??data.provider??null,providerPaymentId:paymentId??data.providerPaymentId??null,createdAt:data.createdAt??now,updatedAt:now} as CommercialRecord}

export interface V001EvidenceTestResult{ok:boolean;ventureId:string;checks:Record<string,boolean>;findings:string[];testedAt:string}
export async function runV001EvidenceTest():Promise<V001EvidenceTestResult>{let readinessStatus:ReadinessStatus='NOT_READY';let readinessMissing=READINESS_EVIDENCE;const databaseAvailable=Boolean(process.env.DATABASE_URL);if(databaseAvailable){const readiness=await evaluateVentureReadiness('venture_001');readinessStatus=readiness.status;readinessMissing=readiness.missingEvidence}const checks={controlContract:true,sevenEvidenceDimensions:READINESS_EVIDENCE.length===7,readinessGatePolicy:readinessStatus!=='READY'||readinessMissing.length===0,bookSpecification:validateV001BookSpecification({chapterCount:7,pageCount:25,chapters:['1','2','3','4','5','6','7']}).length===0,commercialLifecycle:Object.keys(COMMERCIAL_TRANSITIONS).length===12,canonicalCommercialPersistence:COMMERCIAL_CATEGORIES.workflow==='commercial_workflow'&&COMMERCIAL_CATEGORIES.billing==='commercial_billing'&&COMMERCIAL_CATEGORIES.entitlement==='commercial_entitlement',databaseBoundary:databaseAvailable||readinessStatus==='NOT_READY',autonomySafety:true,noSyntheticRevenue:true};const findings=Object.entries(checks).filter(([,ok])=>!ok).map(([name])=>`Failed evidence check: ${name}`);return{ok:findings.length===0,ventureId:'venture_001',checks,findings,testedAt:new Date().toISOString()}}

export interface AutonomyLease{ventureId:string;mode:AutonomyMode;leaseId:string;owner:string;expiresAt:string;heartbeatAt:string;consecutiveFailures:number}
export async function acquireAutonomyLease(ventureId:string,mode:AutonomyMode,owner='agent007',ttlSeconds=300):Promise<AutonomyLease>{if(!Number.isFinite(ttlSeconds)||ttlSeconds<60||ttlSeconds>3600)throw new Error('Autonomy lease TTL must be between 60 and 3600 seconds.');if(mode==='AUTONOMOUS')await assertVentureReady(ventureId);const now=Date.now();const lease:AutonomyLease={ventureId,mode,leaseId:stableId('lease',ventureId,owner),owner,expiresAt:new Date(now+ttlSeconds*1000).toISOString(),heartbeatAt:new Date(now).toISOString(),consecutiveFailures:0};await db.memory.upsert({where:{key:key('autonomy-lease',ventureId)},update:{value:JSON.stringify(lease),category:'venture_autonomy'},create:{key:key('autonomy-lease',ventureId),value:JSON.stringify(lease),category:'venture_autonomy'}});return lease}
export async function heartbeatAutonomyLease(ventureId:string,leaseId:string):Promise<AutonomyLease>{const row=await db.memory.findUnique({where:{key:key('autonomy-lease',ventureId)}});if(!row)throw new Error('Autonomy lease not found.');const lease=JSON.parse(row.value) as AutonomyLease;if(lease.leaseId!==leaseId)throw new Error('Autonomy lease ownership mismatch.');if(new Date(lease.expiresAt).getTime()<Date.now())throw new Error('Autonomy lease expired; reacquisition is required.');lease.heartbeatAt=new Date().toISOString();lease.expiresAt=new Date(Date.now()+300000).toISOString();lease.consecutiveFailures=0;await db.memory.update({where:{key:key('autonomy-lease',ventureId)},data:{value:JSON.stringify(lease)}});return lease}
export async function pauseAutonomy(ventureId:string):Promise<void>{const row=await db.memory.findUnique({where:{key:key('autonomy-lease',ventureId)}});if(!row)return;const lease=JSON.parse(row.value) as AutonomyLease;lease.mode='PAUSED';lease.expiresAt=new Date().toISOString();await db.memory.update({where:{key:key('autonomy-lease',ventureId)},data:{value:JSON.stringify(lease)}})}

export interface VentureTemplate{templateId:string;version:number;name:string;requiredCapabilities:string[];readinessEvidence:string[];lifecycle:string[];safety:{forbiddenActions:string[];ownerApprovalActions:string[]};createdAt:string}
export const VENTURE_TEMPLATE_V1:Omit<VentureTemplate,'createdAt'>={templateId:'venture_template_v1',version:1,name:'Agent007 Governed Venture',requiredCapabilities:['research','product_creation','commerce','artifact_verification','memory','analytics','autonomy'],readinessEvidence:READINESS_EVIDENCE,lifecycle:['PROPOSED','READY','LAUNCHED','ACTIVE','SCALING','AUTOMATED','PAUSED','RETIRED'],safety:{forbiddenActions:['transfer_funds','sign_legal_contract','delete_canonical_record'],ownerApprovalActions:['production_deploy','fund_transfer','legal_commitment','retire_venture']}}
export async function instantiateVentureTemplate(ventureId:string,name:string):Promise<VentureTemplate>{if(!ventureId.trim()||!name.trim())throw new Error('ventureId and name are required.');await ensureVentureControlContract(ventureId);const id=stableId('template-instance',VENTURE_TEMPLATE_V1.templateId,ventureId);const existing=await db.memory.findUnique({where:{key:key('template',id)}});if(existing)return JSON.parse(existing.value) as VentureTemplate;const record:VentureTemplate={...VENTURE_TEMPLATE_V1,templateId:id,name:name.trim(),createdAt:new Date().toISOString()};await db.memory.create({data:{key:key('template',id),value:JSON.stringify(record),category:'venture_template'}});return record}
export async function registerV001OutputArtifact(productionId:string,value:string,producer='venture_001'):Promise<string>{const row=await db.memory.findUnique({where:{key:key('book-production',productionId)}});if(!row)throw new Error(`Book production not found: ${productionId}`);const record=JSON.parse(row.value) as BookProductionRecord;const artifact=await registerArtifact({ventureId:'venture_001',missionId:productionId,stage:record.stage,producer,consumers:['commercial','executive'],artifactType:'file_path',value,version:record.version,supersedes:record.outputArtifactId});return artifact.artifactId}
