import { readFileSync, existsSync } from 'node:fs'

const failures: string[] = []
const required = ['src/lib/ceo-behavioral-policy.ts','src/lib/ceo-response-contract.ts','src/lib/ceo-control-plane-summary.ts','src/lib/ceo-response-finalizer.ts','src/lib/ceo-response-composer.ts','src/lib/ceo-response-persistence.ts','src/lib/ceo-context-composer.ts','src/lib/ceo-conversation-state.ts','src/lib/ceo-context-intelligence.ts','src/lib/ceo-world-model.ts','src/lib/ceo-response-quality-gate.ts','src/lib/ceo-degraded-mode.ts','src/lib/ceo-cognitive-contract.ts','src/lib/ceo-cognitive-lifecycle.ts','src/lib/db.ts','src/app/api/agent/route.ts','tests/ceo-response-finalizer.test.ts','tests/ceo-response-contract.test.ts','docs/CEO-PHASES-1-8-CLOSURE.md','docs/CEO-AUTHORITATIVE-RESPONSE-CONTRACT.md']
for (const file of required) if (!existsSync(file)) failures.push(`Missing Phase 1–8 component: ${file}`)
if (failures.length) { console.error('CEO Phase 1–8 architecture audit FAILED'); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1) }
const read = (file: string) => readFileSync(file, 'utf8')
const policy=read(required[0]), responseContract=read(required[1]), controlPlane=read(required[2]), finalizer=read(required[3]), composer=read(required[4]), persistence=read(required[5]), context=read(required[6]), state=read(required[7]), intelligence=read(required[8]), worldModel=read(required[9]), qualityGate=read(required[10]), degraded=read(required[11]), contract=read(required[12]), lifecycle=read(required[13]), db=read(required[14]), route=read(required[15]), test=read(required[16]), responseTest=read(required[17]), docs=read(required[18]), authoritativeDocs=read(required[19])
if (!policy.includes('CEO_INTERNAL_ARTIFACT_TOKENS') || (policy.match(/CEO_INTERNAL_ARTIFACT_TOKENS/g)??[]).length<2) failures.push('Canonical artifact registry is missing or not used by detection')
for (const token of ['continuous_loop_trace','governed_evolution_cycle','evidence_trace']) if (!policy.includes(token)) failures.push(`Canonical artifact registry missing token coverage: ${token}`)
if (finalizer.includes('STRUCTURED_ARTIFACT_TOKENS')) failures.push('Finalizer contains duplicate artifact-token inventory')
for (const phrase of ['CEO_INTERNAL_ARTIFACT_TOKENS','CeoResponseDecisionEnvelope','CEO_RESPONSE_CANDIDATE_MISMATCH','finalResponseHash','assertFinalResponseInvariant','CEO_FINAL_RESPONSE_ID_MISMATCH']) if (!finalizer.includes(phrase)) failures.push(`Finalizer missing ${phrase}`)
for (const phrase of ['buildCeoResponseCandidate','decideCeoCandidate','controlPlaneSummary','assertCeoResponseDecisionEnvelope']) if (!responseContract.includes(phrase)) failures.push(`Response contract missing ${phrase}`)
for (const phrase of ['export type { CeoControlPlaneSummary }','assertCeoControlPlaneSummary']) if (!controlPlane.includes(phrase)) failures.push(`Control-plane contract missing ${phrase}`)
for (const phrase of ['buildCeoControlPlaneSummary','buildAuthoritativeCeoResponseDecision','finalizeCeoResponseForSurface']) if (!composer.includes(phrase)) failures.push(`Composer missing ${phrase}`)
if (composer.includes('INTERNAL_RESPONSE_PATTERNS')) failures.push('Legacy duplicate response sanitizer remains in composer')
for (const source of [context,state,intelligence,worldModel,qualityGate,degraded]) if (!source.includes('safeConversationRows')) failures.push('A conversation consumer lacks the canonical safe-history boundary')
if (context.includes('deriveCeoConversationState(input.persistedMessages') || context.includes('resolveConversationReferences(normalizedCurrent, input.persistedMessages')) failures.push('Context composer still sends raw persisted rows into cognition')
if (!contract.includes('CeoResponseCandidate') || !contract.includes('CeoQualityDecision') || !contract.includes('CeoControlPlaneSummary')) failures.push('Canonical cognitive contract is missing authoritative response types')
if (!lifecycle.includes('composeCeoResponse')) failures.push('Lifecycle does not pass the candidate through the canonical response composer/finalizer path')
if (!persistence.includes('$transaction') || !persistence.includes('finalResponseHash') || !persistence.includes('finalizationId') || !persistence.includes("action: 'ceo_response_finalized'")) failures.push('Transactional persistence lineage contract is incomplete')
if (!db.includes('export const db')) failures.push('Canonical Prisma client surface missing')
for (const phrase of ['safeConversationRows','persistCeoAssistantMessage','updateCeoAssistantMessage',"sse('answer', { content: response.content", "sse('answer', { content: synthesis.content"]) if (!route.includes(phrase)) failures.push(`Route missing canonical response path: ${phrase}`)
if (route.includes("role: 'assistant', content: response.content")) failures.push('Route still has a direct CEO assistant persistence path bypassing transactional provenance')
if (route.includes("role: 'assistant', content: synthesis.content")) failures.push('Route still has a direct operational assistant persistence path bypassing transactional provenance')
for (const phrase of ['assertFinalResponseInvariant(tampered)','deriveCeoConversationState(rows)','simulatedPersistence','simulatedSseAnswer','simulatedReload']) if (!test.includes(phrase)) failures.push(`Finalizer/path regression coverage missing ${phrase}`)
if (!responseTest.includes('CeoControlPlaneSummary') || !responseTest.includes('CEO_RESPONSE_CANDIDATE_MISMATCH')) failures.push('Authoritative response contract regression coverage incomplete')
for (const phrase of ['Phase 1','Phase 2','Phase 3','Phase 4','Phase 5','Phase 6','Phase 7','Phase 8']) if (!docs.includes(phrase)) failures.push(`Closure document missing ${phrase}`)
for (const phrase of ['ONE IMMUTABLE CANDIDATE OBJECT','ONE IMMUTABLE QUALITY DECISION','DATABASE']) if (!authoritativeDocs.includes(phrase)) failures.push(`Authoritative response contract documentation missing ${phrase}`)
if (failures.length) { console.error('CEO Phase 1–8 architecture audit FAILED'); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1) }
console.log('CEO Phase 1–8 architecture audit PASSED: authoritative candidate/decision envelope, typed control-plane summary, validation-only finalizer, canonical safe-history boundary, transactional persistence lineage, exact SSE/persistence paths, regression proof and governance documentation are present.')
