import { PrismaClient } from '@prisma/client'
import { createCipheriv, createDecipheriv, createHash } from 'node:crypto'

const confirmation = process.env.DR_RESTORE_CONFIRMATION
const mode = process.env.DR_RESTORE_MODE ?? 'dry-run'
const productionUrl = process.env.AGENT007_PRODUCTION_DATABASE_URL
const recoveryUrl = process.env.AGENT007_DR_DATABASE_URL
const backupKey = process.env.BACKUP_ENCRYPTION_KEY?.trim()
if (confirmation !== 'RESTORE_AGENT007_DR') throw new Error('Missing explicit DR_RESTORE_CONFIRMATION=RESTORE_AGENT007_DR')
if (!productionUrl || !recoveryUrl) throw new Error('Both AGENT007_PRODUCTION_DATABASE_URL and AGENT007_DR_DATABASE_URL are required')
if (!backupKey) throw new Error('BACKUP_ENCRYPTION_KEY is required')
if (productionUrl === recoveryUrl) throw new Error('SAFETY STOP: recovery URL equals production URL')

const TABLES = ['ApiKey','AuditLog','BankAccount','BusinessStrategy','ComplianceCheck','ContractDraft','Conversation','CustomSubagent','Customer','IncomeEntry','IncomingCommand','KnowledgeChunk','KnowledgeDoc','MLModel','MarketingCampaign','Memory','Message','MissionTracker','NotificationLog','Opportunity','Partnership','PayPalAccount','PendingManageAction','PhoneConfig','Prediction','RiskRegister','Schedule','ServicePackage','SystemHealth','Transaction','TwoFactorSecret','User','UserSetting','Experiment','PlatformConnection','RiskProfile','ScalingPlan','SentimentLog'] as const
const ORDER = ['User','AuditLog','UserSetting','ApiKey','BankAccount','BusinessStrategy','ComplianceCheck','ContractDraft','Customer','IncomeEntry','IncomingCommand','KnowledgeDoc','KnowledgeChunk','MLModel','MarketingCampaign','Memory','Opportunity','Partnership','PayPalAccount','PendingManageAction','PhoneConfig','Prediction','RiskProfile','RiskRegister','ScalingPlan','ServicePackage','SystemHealth','Transaction','TwoFactorSecret','Experiment','PlatformConnection','MissionTracker','SentimentLog','Schedule','CustomSubagent','Conversation','Message','NotificationLog'] as const
const SECRETS: Record<string,string[]> = {ApiKey:['key'],BankAccount:['accountNumber','routingNumber'],PayPalAccount:['clientSecret'],PhoneConfig:['callmebotApiKey','emailImapPassword'],PlatformConnection:['apiKey','apiSecret','accessToken'],Transaction:['rawPayload'],TwoFactorSecret:['secret','backupCodes'],User:['passwordHash']}
const key=()=>/^[0-9a-fA-F]{64}$/.test(backupKey!)?Buffer.from(backupKey!,'hex'):createHash('sha256').update(backupKey!).digest()
const enc=(v:unknown)=>{const iv=Buffer.from(Array.from({length:12},()=>Math.floor(Math.random()*256)));const c=createCipheriv('aes-256-gcm',key(),iv);const d=Buffer.concat([c.update(JSON.stringify(v)),c.final()]);return [iv,c.getAuthTag(),d].map(x=>x.toString('base64url')).join('.')}
const dec=(s:string)=>{const [i,t,d]=s.split('.');if(!i||!t||!d)throw new Error('Invalid encrypted secret envelope');const c=createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64url'));c.setAuthTag(Buffer.from(t,'base64url'));return JSON.parse(Buffer.concat([c.update(Buffer.from(d,'base64url')),c.final()]).toString())}
const norm=(v:unknown):unknown=>v instanceof Date?v.toISOString():Array.isArray(v)?v.map(norm):v&&typeof v==='object'?Object.fromEntries(Object.entries(v as Record<string,unknown>).map(([k,x])=>[k,norm(x)])):v
const sanitize=(v:unknown):unknown=>typeof v==='string'?v.replace(/(Bearer\s+)[A-Za-z0-9._~+/=-]+/gi,'$1[REDACTED]').replace(/([?&](?:access_token|api[_-]?key|apikey|client_secret|refresh_token|id_token|auth_token|authorization|password|passwd|secret|token)=)[^&#\s"'<>]+/gi,'$1[REDACTED]'):Array.isArray(v)?v.map(sanitize):v&&typeof v==='object'?Object.fromEntries(Object.entries(v as Record<string,unknown>).map(([k,x])=>[k,/(access[_-]?token|api[_-]?key|apikey|client[_-]?secret|refresh[_-]?token|id[_-]?token|auth[_-]?token|password|passwd|secret|authorization)/i.test(k)?(x==null||x===''?x:'[REDACTED]'):sanitize(x)])):v
const canon=(v:unknown):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(canon).join(',')}]`:`{${Object.keys(v as Record<string,unknown>).sort().map(k=>`${JSON.stringify(k)}:${canon((v as Record<string,unknown>)[k])}`).join(',')}}`
const hash=(v:unknown)=>createHash('sha256').update(canon(v)).digest('hex')
const host=(u:string)=>{try{return new URL(u).hostname}catch{return ''}}
async function cols(c:PrismaClient){return c.$queryRaw<Array<{table_name:string;column_name:string;data_type:string}>>`SELECT table_name,column_name,data_type FROM information_schema.columns WHERE table_schema='public'`}
function schemaFingerprint(rows:Array<{table_name:string;column_name:string;data_type:string}>){return hash(rows.map(x=>({table_name:x.table_name,column_name:x.column_name,data_type:x.data_type})).sort((a,b)=>`${a.table_name}.${a.column_name}.${a.data_type}`.localeCompare(`${b.table_name}.${b.column_name}.${b.data_type}`)))}
function castFor(dataType:string){switch(dataType){case 'date':return 'date';case 'timestamp without time zone':return 'timestamp';case 'timestamp with time zone':return 'timestamptz';case 'time without time zone':return 'time';case 'time with time zone':return 'timetz';default:return ''}}
function restoreValue(value:unknown,dataType:string){if(value==null||typeof value!=='string')return value;if(dataType==='date')return value.slice(0,10);if(dataType==='timestamp without time zone')return value.replace(/Z$/,'');if(dataType==='time without time zone'||dataType==='time with time zone'){const m=value.match(/T(\d{2}:\d{2}:\d{2}(?:\.\d+)?)(Z|[+-]\d{2}:\d{2})?$/);return m?`${m[1]}${m[2]??''}`:value}return value}
async function makeBackup(c:PrismaClient){const tables:Record<string,any>={};let records=0;for(const table of TABLES){const rows=await c.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM \"${table}\"`);const secrets=SECRETS[table]??[];const clean:any[]=[];const encrypted:any[]=[];for(const raw of rows){const row=norm(raw) as Record<string,unknown>;const r={...row};const e:any={};for(const col of secrets)if(col in r&&r[col]!=null){e[col]=enc(r[col]);delete r[col]}clean.push(sanitize(r));if(Object.keys(e).length)encrypted.push({id:String(row.id),fields:e})}tables[table]={rows:clean,encryptedSecrets:encrypted,count:rows.length};records+=rows.length}const schema=await cols(c);const payload={backupVersion:'2.1',application:'Agent007 AI',generatedAt:new Date().toISOString(),schema:{fingerprint:schemaFingerprint(schema),expectedModels:TABLES.length,exportedModels:TABLES.length},totals:{models:TABLES.length,records},tables};return {...payload,integrity:{algorithm:'SHA-256',checksum:hash(payload)}}}
async function main(){const ph=host(productionUrl!),rh=host(recoveryUrl!);if(!ph||!rh||ph===rh)throw new Error('SAFETY STOP: production and recovery hosts could not be positively distinguished');const prod=new PrismaClient({datasources:{db:{url:productionUrl}}});const dr=new PrismaClient({datasources:{db:{url:recoveryUrl}}});try{await prod.$queryRaw`SELECT 1`;await dr.$queryRaw`SELECT 1`;const b=await makeBackup(prod);const sc=await cols(prod),rc=await cols(dr);const sf=schemaFingerprint(sc),rf=schemaFingerprint(rc);const ss=new Set(sc.map(x=>`${x.table_name}.${x.column_name}.${x.data_type}`)),rs=new Set(rc.map(x=>`${x.table_name}.${x.column_name}.${x.data_type}`));const missing=[...ss].filter(x=>!rs.has(x)).sort().slice(0,200),extra=[...rs].filter(x=>!ss.has(x)).sort().slice(0,200);console.log(JSON.stringify({preflight:{sourceFingerprint:sf,recoveryFingerprint:rf,schemaMatch:sf===rf,sourceColumns:ss.size,recoveryColumns:rs.size,missingInRecovery:missing,extraInRecovery:extra}},null,2));if(sf!==rf)throw new Error('DR schema mismatch. Restore refused; see missingInRecovery/extraInRecovery.');const columnTypes=new Map(sc.map(x=>[`${x.table_name}.${x.column_name}`,x.data_type]));const dry=mode!=='restore';let inserted=0,wouldInsert=0,models=0;for(const table of ORDER){const block=b.tables[table];if(!block)continue;models++;if(dry){wouldInsert+=block.rows.length;continue}const sm=new Map<string,any>((block.encryptedSecrets??[]).map((x:any)=>[String(x.id),x.fields??{}]));for(const raw of block.rows){const row={...raw} as Record<string,unknown>;for(const [col,p] of Object.entries(sm.get(String(row.id))??{}))row[col]=dec(p as string);const cs=Object.keys(row),q=cs.map(c=>`\"${c.replace(/\"/g,'\"\"')}\"`).join(','),p=cs.map((c,i)=>{const dataType=columnTypes.get(`${table}.${c}`)??'';const cast=castFor(dataType);return cast?`$${i+1}::${cast}`:`$${i+1}`}).join(',');const values=cs.map(c=>restoreValue(row[c],columnTypes.get(`${table}.${c}`)??''));try{await dr.$executeRawUnsafe(`INSERT INTO \"${table}\" (${q}) VALUES (${p}) ON CONFLICT DO NOTHING`,...values);inserted++}catch(e){throw new Error(`RESTORE INSERT FAILED: table=${table} id=${String(row.id)} error=${e instanceof Error?e.message:String(e)}`)}}}const verification:Record<string,number>={};for(const table of TABLES){const r=await dr.$queryRawUnsafe<Array<{count:bigint}>>(`SELECT COUNT(*)::bigint AS count FROM \"${table}\"`);verification[table]=Number(r[0]?.count??0)}console.log(JSON.stringify({ok:true,mode:dry?'dry-run':'restore',checksum:b.integrity.checksum,source:{models:b.totals.models,records:b.totals.records},recovery:{models:Object.keys(verification).length,records:Object.values(verification).reduce((a,x)=>a+x,0)},stats:{models,wouldInsert,inserted}},null,2))}finally{await Promise.allSettled([prod.$disconnect(),dr.$disconnect()])}}
main().catch(e=>{console.error(e);process.exitCode=1})
